Repository dlt-hub/dlt, pull requests merged in 2024-07, with the labels that each got.

#1528 docs: Fixed markdown issue in duckdb.md
  docs/website/docs/dlt-ecosystem/destinations/duckdb.md
Labels: bug, documentation

#1531 rest_api: add a quick example to rest_api docs
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
Labels: documentation

#1538 Update grouping-resources.md docs
  docs/website/docs/tutorial/grouping-resources.md
Labels: bug, documentation

#1532 Docs: update integrations and verified sources pages
  docs/website/docs/dlt-ecosystem/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/index.md
  docs/website/sidebars.js
Labels: documentation

#1516 feat(filesystem): use only netloc and scheme for fingerprint
  dlt/common/storages/configuration.py
  tests/load/filesystem/test_filesystem_client.py
Labels: sprint

#1537 removes deprecated credentials argument from Pipeline
  dlt/common/destination/reference.py
  dlt/pipeline/__init__.py
  dlt/pipeline/pipeline.py
  dlt/pipeline/warnings.py
  docs/examples/archive/credentials/explicit.py
  docs/examples/archive/quickstart.py
  docs/website/docs/dlt-ecosystem/destinations/duckdb.md
  tests/extract/test_incremental.py
  tests/helpers/airflow_tests/test_airflow_wrapper.py
  tests/helpers/airflow_tests/test_join_airflow_scheduler.py
  tests/load/duckdb/test_duckdb_client.py
  tests/load/filesystem/test_aws_credentials.py
  tests/load/filesystem/test_gcs_credentials.py
  tests/load/pipeline/test_pipelines.py
  tests/pipeline/test_pipeline.py
  tests/pipeline/test_schema_contracts.py
Labels: sprint

#1510 Added Postgres replication verified sources docs
  docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
  docs/website/sidebars.js
Labels: documentation

#1501 Extend orjson dependency allowed range with excluded versions
  poetry.lock
  pyproject.toml
Labels: sprint

#1526 Fix/qdrant tests in CI
  .github/workflows/test_doc_snippets.yml
  .github/workflows/test_local_destinations.yml
  dlt/common/destination/reference.py
  dlt/destinations/impl/qdrant/configuration.py
  dlt/destinations/impl/qdrant/exceptions.py
  dlt/destinations/impl/qdrant/factory.py
  dlt/destinations/impl/qdrant/qdrant_client.py
  dlt/load/load.py
  dlt/pipeline/pipeline.py
  docs/examples/qdrant_zendesk/qdrant_zendesk.py
  docs/tools/prepare_examples_tests.py
  tests/conftest.py
  tests/load/pipeline/test_arrow_loading.py
  tests/load/pipeline/test_restore_state.py
  tests/load/qdrant/test_pipeline.py
  tests/load/utils.py
Labels: sprint

#1536 improves collision detection when naming convention changes
  dlt/cli/_dlt.py
  dlt/cli/pipeline_command.py
  dlt/common/configuration/paths.py
  dlt/common/json/__init__.py
  dlt/common/known_env.py
  dlt/common/normalizers/utils.py
  dlt/common/runners/stdout.py
  dlt/common/runtime/collector.py
  dlt/common/schema/schema.py
  dlt/common/schema/utils.py
  dlt/common/storages/fsspec_filesystem.py
  dlt/common/storages/load_package.py
  dlt/common/utils.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/bigquery/sql_client.py
  dlt/destinations/impl/clickhouse/sql_client.py
  dlt/destinations/impl/databricks/sql_client.py
  dlt/destinations/impl/destination/factory.py
  dlt/destinations/impl/dremio/sql_client.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/destinations/impl/lancedb/lancedb_client.py
  dlt/destinations/impl/mssql/sql_client.py
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/destinations/impl/synapse/sql_client.py
  dlt/destinations/sql_client.py
  dlt/extract/decorators.py
  dlt/extract/extract.py
  dlt/extract/incremental/__init__.py
  dlt/extract/source.py
  dlt/helpers/airflow_helper.py
  dlt/helpers/dbt/runner.py
  dlt/load/load.py
  dlt/load/utils.py
  dlt/normalize/worker.py
  dlt/pipeline/drop.py
  dlt/pipeline/helpers.py
  dlt/pipeline/pipeline.py
  dlt/sources/helpers/requests/retry.py
  poetry.lock
  pyproject.toml
  tests/cli/common/test_cli_invoke.py
  tests/common/configuration/test_toml_provider.py
  tests/common/schema/test_normalize_identifiers.py
  tests/common/test_json.py
  tests/extract/test_sources.py
  tests/load/filesystem/test_filesystem_common.py
  tests/load/lancedb/test_pipeline.py
  tests/load/pipeline/test_bigquery.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/load/pipeline/test_refresh_modes.py
  tests/load/test_job_client.py
  tests/load/test_sql_client.py
  tests/load/utils.py
  tests/pipeline/test_dlt_versions.py
  tests/pipeline/test_drop_helpers.py
  tests/pipeline/test_pipeline.py
  tests/pipeline/utils.py
  tox.ini
Labels: sprint

#1547 selects all tables from info schema if number of tables > threshold
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/job_client_impl.py
  tests/conftest.py
  tests/load/pipeline/test_pipelines.py
Labels: ci full

#1555 adds missing docs / tests and configurable staging dataset name
  dlt/common/destination/capabilities.py
  dlt/common/destination/reference.py
  dlt/common/schema/schema.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/bigquery/configuration.py
  dlt/destinations/impl/bigquery/factory.py
  dlt/destinations/impl/bigquery/sql_client.py
  dlt/destinations/impl/clickhouse/clickhouse.py
  dlt/destinations/impl/clickhouse/sql_client.py
  dlt/destinations/impl/databricks/databricks.py
  dlt/destinations/impl/databricks/sql_client.py
  dlt/destinations/impl/dremio/dremio.py
  dlt/destinations/impl/dremio/sql_client.py
  dlt/destinations/impl/duckdb/duck.py
  dlt/destinations/impl/duckdb/sql_client.py
  dlt/destinations/impl/lancedb/lancedb_client.py
  dlt/destinations/impl/motherduck/motherduck.py
  dlt/destinations/impl/motherduck/sql_client.py
  dlt/destinations/impl/mssql/mssql.py
  dlt/destinations/impl/mssql/sql_client.py
  dlt/destinations/impl/postgres/factory.py
  dlt/destinations/impl/postgres/postgres.py
  dlt/destinations/impl/postgres/sql_client.py
  dlt/destinations/impl/qdrant/qdrant_client.py
  dlt/destinations/impl/redshift/redshift.py
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/destinations/impl/snowflake/sql_client.py
  dlt/destinations/impl/synapse/synapse.py
  dlt/destinations/impl/weaviate/weaviate_client.py
  dlt/destinations/job_client_impl.py
  dlt/destinations/sql_client.py
  dlt/destinations/sql_jobs.py
  dlt/normalize/worker.py
  docs/website/docs/dlt-ecosystem/destinations/athena.md
  docs/website/docs/dlt-ecosystem/destinations/bigquery.md
  docs/website/docs/dlt-ecosystem/destinations/mssql.md
  docs/website/docs/dlt-ecosystem/destinations/postgres.md
  docs/website/docs/dlt-ecosystem/destinations/redshift.md
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
  docs/website/docs/dlt-ecosystem/staging.md
  docs/website/docs/general-usage/naming-convention.md
  docs/website/docs/reference/performance.md
  docs/website/docs/running-in-production/running.md
  pyproject.toml
  tests/cases.py
  tests/common/schema/test_inference.py
  tests/common/test_destination.py
  tests/load/bigquery/test_bigquery_table_builder.py
  tests/load/pipeline/test_pipelines.py
  tests/load/postgres/test_postgres_table_builder.py
  tests/load/redshift/test_redshift_table_builder.py
  tests/load/snowflake/test_snowflake_table_builder.py
  tests/load/test_job_client.py
  tests/load/test_sql_client.py
  tests/pipeline/test_dlt_versions.py
  tests/pipeline/test_pipeline.py
Labels: ci full, sprint

#1467 Document sql source reflection level and type adapter
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
Labels: documentation

#1582 query tagging for snowflake
  dlt/common/pipeline.py
  dlt/destinations/impl/snowflake/configuration.py
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/destinations/impl/snowflake/sql_client.py
  dlt/destinations/job_client_impl.py
  dlt/destinations/sql_client.py
  dlt/load/load.py
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
  tests/load/pipeline/test_snowflake_pipeline.py
  tests/load/snowflake/test_snowflake_client.py
Labels: community, ci full

#1496 Support Open Source ClickHouse Deployments
  .github/workflows/test_destination_clickhouse.yml
  dlt/destinations/impl/clickhouse/clickhouse.py
  dlt/destinations/impl/clickhouse/clickhouse_adapter.py
  dlt/destinations/impl/clickhouse/configuration.py
  dlt/destinations/impl/clickhouse/factory.py
  dlt/destinations/impl/clickhouse/sql_client.py
  dlt/destinations/impl/clickhouse/typing.py
  dlt/destinations/impl/clickhouse/utils.py
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
  tests/load/clickhouse/clickhouse-compose.yml
  tests/load/clickhouse/test_clickhouse_adapter.py
  tests/load/clickhouse/test_clickhouse_configuration.py
  tests/load/clickhouse/test_clickhouse_table_builder.py
  tests/load/clickhouse/utils.py
Labels: enhancement, tech-debt

#1543 Add to docs docs configuring file format options
  docs/website/docs/dlt-ecosystem/file-formats/_set_the_format.mdx
  docs/website/docs/dlt-ecosystem/file-formats/csv.md
  docs/website/docs/dlt-ecosystem/file-formats/insert-format.md
  docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  docs/website/docs/dlt-ecosystem/transformations/sql.md
Labels: documentation

#1598 fix - enables query tagging
  dlt/destinations/impl/snowflake/configuration.py
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/destinations/impl/snowflake/sql_client.py
  dlt/destinations/job_client_impl.py
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
  tests/load/pipeline/test_snowflake_pipeline.py
  tests/load/snowflake/test_snowflake_client.py
Labels: bug, ci full

#1602 Docs: remove the link to the legacy blog from the docs navigation
  docs/website/docusaurus.config.js
Labels: documentation

#1524 docs/505 updates documentation on custom hooks in response_actions
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/general-usage/http/rest-client.md
Labels: documentation

#1611 Docs: rest_api: fix broken snippets in response_actions
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
Labels: bug, documentation

#1608 Add note that pg_replication doesn't support scd2
  docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
Labels: documentation

#1634 Allows using JSONResponsePaginator in place of JSONLinkPaginator
  dlt/sources/helpers/rest_client/paginators.py
Labels: bug

#1641 Fix/1606 fixes validator incremental step order
  dlt/common/json/__init__.py
  dlt/common/libs/pydantic.py
  dlt/common/logger.py
  dlt/extract/incremental/__init__.py
  dlt/extract/items.py
  dlt/extract/pipe.py
  dlt/extract/validation.py
  dlt/pipeline/trace.py
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
  docs/website/docs/general-usage/incremental-loading.md
  tests/extract/test_extract_pipe.py
  tests/extract/test_incremental.py
  tests/extract/test_validation.py
  tests/extract/utils.py
  tests/libs/test_pydantic.py
  tests/pipeline/test_pipeline_extra.py
  tests/pipeline/test_pipeline_trace.py
Labels: community

#1642 Feat/1596 adds custom docs config provider
  dlt/cli/init_command.py
  dlt/cli/telemetry_command.py
  dlt/common/configuration/accessors.py
  dlt/common/configuration/providers/__init__.py
  dlt/common/configuration/providers/airflow.py
  dlt/common/configuration/providers/dictionary.py
  dlt/common/configuration/providers/google_secrets.py
  dlt/common/configuration/providers/toml.py
  dlt/common/configuration/providers/vault.py
  dlt/common/configuration/specs/config_providers_context.py
  dlt/common/configuration/utils.py
  docs/examples/custom_config_provider/.dlt/config.toml
  docs/examples/custom_config_provider/__init__.py
  docs/examples/custom_config_provider/custom_config_provider.py
  docs/examples/custom_config_provider/profiles.yaml
  docs/website/docs/general-usage/credentials/config_providers.md
  tests/common/cases/configuration/config.yml
  tests/common/configuration/test_accessors.py
  tests/common/configuration/test_inject.py
  tests/common/configuration/test_toml_provider.py
  tests/helpers/airflow_tests/test_airflow_provider.py
  tests/helpers/airflow_tests/utils.py
  tests/helpers/providers/test_google_secrets_provider.py
Labels: support

#1640 Allow prereleases for LancedB
  poetry.lock
  pyproject.toml
Labels: dependency update

#1609 Feat/1593 rest_client: allow setting of request kwargs
  dlt/sources/helpers/rest_client/client.py
  tests/sources/helpers/rest_client/test_client.py
Labels: enhancement

#1652 Update book a call link description
  docs/website/docs/_book-onboarding-call.md
  docs/website/docs/dlt-ecosystem/verified-sources/index.md
Labels: documentation

#1649 docs: documents new `convert` parameter in rest_api source incremental config
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
Labels: documentation
