Repository dlt-hub/dlt, pull requests merged in 2024-05, with the labels that each got.

#1284 Extend motherduck client configuration to pass custom user agent
  dlt/destinations/impl/duckdb/configuration.py
  dlt/destinations/impl/motherduck/configuration.py
  docs/website/docs/dlt-ecosystem/destinations/motherduck.md
  tests/load/duckdb/test_motherduck_client.py
Labels: enhancement

#1313 Docs/google ads
  docs/website/docs/dlt-ecosystem/verified-sources/google_ads.md
Labels: documentation

#1321 adds std pipe iterator for stdin and stderr
  dlt/common/logger.py
  dlt/common/runners/stdout.py
  tests/common/runners/test_std_pipes.py
  tests/common/scripts/stderr_counter.py
Labels: support

#1297 Accept :memory: mode for credentials parameter in duckdb factory
  dlt/destinations/impl/duckdb/configuration.py
  dlt/destinations/impl/duckdb/exceptions.py
  dlt/destinations/impl/duckdb/factory.py
  docs/website/docs/dlt-ecosystem/destinations/duckdb.md
  tests/load/duckdb/test_duckdb_client.py
Labels: bug, community

#1151 Add a topic guide for the `RESTClient` class
  docs/website/docs/general-usage/http/overview.md
  docs/website/docs/general-usage/http/requests.md
  docs/website/docs/general-usage/http/rest-client.md
  docs/website/docs/reference/performance.md
  docs/website/sidebars.js
Labels: documentation, sprint

#1341 Docs: fix titles capitalization in sidebar and page headers
  docs/examples/qdrant_zendesk/qdrant_zendesk.py
  docs/website/docs/build-a-pipeline-tutorial.md
  docs/website/docs/dlt-ecosystem/file-formats/csv.md
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  docs/website/docs/dlt-ecosystem/verified-sources/index.md
  docs/website/docs/general-usage/credentials/config_providers.md
  docs/website/docs/general-usage/credentials/config_specs.md
  docs/website/docs/general-usage/credentials/configuration.md
  docs/website/docs/general-usage/glossary.md
  docs/website/docs/general-usage/schema-contracts.md
  docs/website/docs/general-usage/schema-evolution.md
  docs/website/docs/reference/command-line-interface.md
  docs/website/docs/reference/frequently-asked-questions.md
  docs/website/docs/tutorial/grouping-resources.md
  docs/website/docs/walkthroughs/zendesk-weaviate.md
Labels: documentation

#1343 RESTClient: docs: add PageNumberPaginator, update OffsetPaginator
  docs/website/docs/general-usage/http/rest-client.md
Labels: documentation, sprint

#1306 ignores table options on ALTER TABLE
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/bigquery/bigquery_adapter.py
  tests/load/bigquery/test_bigquery_table_builder.py
Labels: bug

#1228 Docs: Freshdesk documentation
  docs/website/docs/dlt-ecosystem/verified-sources/freshdesk.md
  docs/website/sidebars.js
Labels: documentation

#1296 Docs: Updated runnning docs with how to configure external logger
  docs/website/docs/running-in-production/running.md
Labels: documentation, community

#1330 Added info about how to "Configure multiple destinations in a pipeline"
  docs/website/blog/2024-05-07-on-orchestrators.md
  docs/website/docs/general-usage/destination.md
Labels: documentation, community

#1344 Catch MissingDependencyException in telemetry and check for sentry_sdk
  dlt/common/runtime/telemetry.py
Labels: bug

#1326 Streamlit caching and session state store fixes
  dlt/helpers/streamlit_app/blocks/show_data.py
  dlt/helpers/streamlit_app/blocks/table_hints.py
  dlt/helpers/streamlit_app/pages/dashboard.py
  dlt/helpers/streamlit_app/utils.py
  dlt/helpers/streamlit_app/widgets/schema.py
Labels: enhancement, community

#1348 exposes merge columns
  dlt/common/schema/utils.py
  dlt/extract/extractors.py
  dlt/extract/hints.py
  dlt/sources/helpers/rest_client/auth.py
  dlt/sources/helpers/rest_client/client.py
  dlt/sources/helpers/rest_client/detector.py
  dlt/sources/helpers/rest_client/exceptions.py
  dlt/sources/helpers/rest_client/paginators.py
  pyproject.toml
  tests/common/schema/test_merges.py
  tests/common/test_validation.py
  tests/load/weaviate/test_pipeline.py
  tests/sources/helpers/rest_client/test_detector.py
Labels: sprint

#1358 RESTClient: add an example for creating a custom POST paginator
  docs/website/docs/general-usage/http/rest-client.md
Labels: sprint

#1308 Add rest_api verified source documentation
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/sidebars.js
Labels: documentation, sprint

#1367 RESTClient: docs: add the troubleshooting section
  docs/website/docs/general-usage/http/rest-client.md
Labels: documentation

#1351 Replace weather api example with github in create a pipeline walkthrough
  docs/website/docs/walkthroughs/create-a-pipeline.md
Labels: documentation

#1373 RESTClient: docs: Fixed snippet definition
  docs/website/docs/general-usage/http/rest-client.md
Labels: bug, documentation

#1386 docs: destination tables: elaborate on example code
  docs/website/docs/general-usage/destination-tables.md
Labels: documentation

#1392 Fix snippet linting errors
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/general-usage/http/rest-client.md
  docs/website/docs/walkthroughs/create-a-pipeline.md
Labels: bug, documentation

#1399 RESTClient: Added "values" to the data pattern of the rest_api helper
  dlt/sources/helpers/rest_client/detector.py
Labels: enhancement

#1362 rest_api: add response_actions documentation
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
Labels: documentation

#1287 Update the tutorial to use `rest_client.paginate` for pagination
  docs/website/docs/tutorial/grouping-resources.md
  docs/website/docs/tutorial/load-data-from-an-api.md
Labels: documentation, sprint

#1404 fix command to install dlt
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
Labels: documentation

#1383 [master] improves sql database docs
  docs/website/docs/dlt-ecosystem/destinations/mssql.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
Labels: documentation

#1409 rest_api: docs: Mention JSONPath in resolve conf
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
Labels: documentation, enhancement

#1410 Updated installation command in destination docs and a few others
  docs/website/docs/dlt-ecosystem/destinations/athena.md
  docs/website/docs/dlt-ecosystem/destinations/bigquery.md
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
  docs/website/docs/dlt-ecosystem/destinations/databricks.md
  docs/website/docs/dlt-ecosystem/destinations/dremio.md
  docs/website/docs/dlt-ecosystem/destinations/duckdb.md
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  docs/website/docs/dlt-ecosystem/destinations/motherduck.md
  docs/website/docs/dlt-ecosystem/destinations/mssql.md
  docs/website/docs/dlt-ecosystem/destinations/postgres.md
  docs/website/docs/dlt-ecosystem/destinations/qdrant.md
  docs/website/docs/dlt-ecosystem/destinations/redshift.md
  docs/website/docs/dlt-ecosystem/destinations/synapse.md
  docs/website/docs/dlt-ecosystem/destinations/weaviate.md
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  docs/website/docs/general-usage/data-enrichments/currency_conversion_data_enrichment.md
  docs/website/docs/general-usage/data-enrichments/url-parser-data-enrichment.md
  docs/website/docs/general-usage/data-enrichments/user_agent_device_data_enrichment.md
Labels: documentation

#1420 Link rest_api & OpenAPI generator from helpers section in the docs
  docs/website/docs/general-usage/http/overview.md
Labels: documentation

#1371 rest_api: add troubleshooting section
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
Labels: documentation
