Repository dlt-hub/dlt, pull requests merged in 2024-03, with the labels that each got.

#1001 Edit arrow-pandas.md and fix a typo
  docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
Labels: documentation

#1012 clear normalized package in case it already existed
  dlt/common/schema/schema.py
  dlt/common/schema/utils.py
  dlt/common/storages/live_schema_storage.py
  dlt/common/storages/load_package.py
  dlt/normalize/normalize.py
  tests/common/schema/test_schema.py
  tests/normalize/test_normalize.py
Labels: bug, community

#1013 fix import schema yaml
  .github/workflows/test_common.yml
  dlt/common/storages/live_schema_storage.py
  dlt/common/storages/schema_storage.py
  dlt/extract/extract.py
  dlt/pipeline/pipeline.py
  tests/pipeline/test_import_export_schema.py
  tests/pipeline/test_pipeline.py
Labels: bug, community

#1062 simplifies and fixes incremental / fixes #971
  dlt/extract/incremental/__init__.py
  dlt/extract/incremental/transform.py
  docs/website/docs/examples/incremental_loading/code/zendesk-snippets.py
  docs/website/docs/general-usage/incremental-loading.md
  tests/common/test_validation.py
  tests/extract/test_incremental.py
Labels: bug, community

#1056 Docs: Add note about google secret name normalization
  docs/website/docs/general-usage/credentials/config_providers.md
Labels: documentation

#1112 splits pandas and arrow imports
  .github/workflows/test_common.yml
  dlt/common/libs/pandas.py
  dlt/common/libs/pandas_sql.py
  dlt/common/libs/pyarrow.py
  dlt/destinations/sql_client.py
  dlt/extract/extractors.py
  dlt/extract/incremental/transform.py
  dlt/extract/wrappers.py
  tests/pipeline/test_pipeline_extra.py
Labels: bug

#1124 Remove old streamlit app
  dlt/helpers/streamlit_helper.py
Labels: tech-debt

#1120 Add example link to the custom destination page
  docs/tools/README.md
  docs/tools/fix_grammar_gpt.py
  docs/website/docs/dlt-ecosystem/destinations/destination.md
  docs/website/docs/general-usage/destination.md
  docs/website/docs/intro.md
  docs/website/docs/walkthroughs/create-new-destination.md
Labels: documentation

#1099 Docs/scraping docs
  docs/website/docs/dlt-ecosystem/verified-sources/scrapy.md
  docs/website/sidebars.js
Labels: documentation

#1118 Docs: Document incremental definition via config.toml
  docs/website/docs/general-usage/incremental-loading.md
Labels: documentation

#1141 Add RESTClient:
  dlt/sources/helpers/requests/__init__.py
  dlt/sources/helpers/rest_client/__init__.py
  dlt/sources/helpers/rest_client/auth.py
  dlt/sources/helpers/rest_client/client.py
  dlt/sources/helpers/rest_client/detector.py
  dlt/sources/helpers/rest_client/exceptions.py
  dlt/sources/helpers/rest_client/paginators.py
  dlt/sources/helpers/rest_client/typing.py
  dlt/sources/helpers/rest_client/utils.py
  poetry.lock
  pyproject.toml
  tests/sources/helpers/rest_client/__init__.py
  tests/sources/helpers/rest_client/conftest.py
  tests/sources/helpers/rest_client/private_key.pem
  tests/sources/helpers/rest_client/test_client.py
  tests/sources/helpers/rest_client/test_detector.py
  tests/sources/helpers/rest_client/test_paginators.py
  tests/sources/helpers/rest_client/test_requests_paginate.py
  tests/sources/helpers/rest_client/test_utils.py
Labels: enhancement

#1130 docs: add typechecking to embedded snippets
  docs/tools/check_embedded_snippets.py
  docs/tools/lint_setup/template.py
  docs/tools/utils.py
  docs/website/blog/2023-08-24-dlt-etlt.md
  docs/website/blog/2023-10-26-dlt-prefect.md
  docs/website/blog/2023-11-01-dlt-dagster.md
  docs/website/blog/2023-11-22-dlt-webhooks-event-based-ingestion.md
  docs/website/blog/2024-01-15-dlt-dbt-runner-on-cloud-functions.md
  docs/website/docs/dlt-ecosystem/destinations/destination.md
  docs/website/docs/dlt-ecosystem/verified-sources/airtable.md
  docs/website/docs/dlt-ecosystem/verified-sources/chess.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem.md
  docs/website/docs/dlt-ecosystem/verified-sources/jira.md
  docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md
  docs/website/docs/general-usage/credentials/config_specs.md
  docs/website/docs/general-usage/customising-pipelines/pseudonymizing_columns.md
  docs/website/docs/general-usage/customising-pipelines/renaming_columns.md
  docs/website/docs/general-usage/data-enrichments/user_agent_device_data_enrichment.md
  docs/website/docs/general-usage/resource.md
  docs/website/docs/general-usage/schema-contracts.md
  docs/website/docs/general-usage/schema-evolution.md
  docs/website/docs/general-usage/schema.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-gcp-cloud-function-as-webhook.md
  mypy.ini
Labels: documentation
