Repository dlt-hub/dlt, pull requests merged in 2024-10, with the labels that each got.

#1845 Docs: Add sftp option for filesystem source
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/index.md
  docs/website/docs/tutorial/filesystem.md
  docs/website/sidebars.js
Labels: documentation

#1898 Docs: sort core sources in the sidebar by usage
  docs/website/sidebars.js
Labels: documentation

#1900 Added troubleshooting section to filesystem docs
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
Labels: documentation

#1912 Docs: fix a typo in credentials/advanced.md
  docs/website/docs/general-usage/credentials/advanced.md
Labels: documentation

#1908 docs: grammar fix pages 100 - 120
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
  docs/website/docs/dlt-ecosystem/visualizations/exploring-the-data.md
  docs/website/docs/examples/index.md
  docs/website/docs/reference/command-line-interface.md
  docs/website/docs/reference/frequently-asked-questions.md
  docs/website/docs/reference/installation.md
  docs/website/docs/reference/performance.md
  docs/website/docs/reference/telemetry.md
  docs/website/docs/reference/tracing.md
  docs/website/docs/running-in-production/alerting.md
  docs/website/docs/running-in-production/monitoring.md
  docs/website/docs/running-in-production/running.md
  docs/website/docs/running-in-production/tracing.md
Labels: documentation

#1910 Docs: fix the code snippet in credentials/setup.md
  docs/website/docs/general-usage/credentials/setup.md
Labels: documentation

#1913 docs: final grammar fix! pages 120-139
  docs/website/docs/reference/explainers/airflow-gcp-cloud-composer.md
  docs/website/docs/reference/explainers/how-dlt-works.md
  docs/website/docs/walkthroughs/add-a-verified-source.md
  docs/website/docs/walkthroughs/add-incremental-configuration.md
  docs/website/docs/walkthroughs/add_credentials.md
  docs/website/docs/walkthroughs/adjust-a-schema.md
  docs/website/docs/walkthroughs/create-a-pipeline.md
  docs/website/docs/walkthroughs/create-new-destination.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-gcp-cloud-function-as-webhook.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-airflow-composer.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-dagster.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-github-actions.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-google-cloud-functions.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-kestra.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-prefect.md
  docs/website/docs/walkthroughs/dispatch-to-multiple-tables.md
  docs/website/docs/walkthroughs/run-a-pipeline.md
  docs/website/docs/walkthroughs/share-a-dataset.md
  docs/website/docs/walkthroughs/zendesk-weaviate.md
Labels: documentation

#1738 Replace AuthBase with AuthConfigBase in example
  docs/website/docs/general-usage/http/rest-client.md
Labels: documentation

#1835 Docs: make naming consistent in the cloud storage & file system source
  docs/website/docs/dlt-ecosystem/file-formats/csv.md
  docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/index.md
  docs/website/sidebars.js
Labels: documentation

#1905 Add redirect from walkthroughs
  docs/website/netlify.toml
Labels: documentation

#1923 Feat/1922 rest api source add mulitple path parameters
  dlt/sources/rest_api/__init__.py
  dlt/sources/rest_api/config_setup.py
  tests/sources/rest_api/configurations/test_resolve_config.py
Labels: enhancement

#1929 Docs: add section on resolving multiple path parameters
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
Labels: documentation

#1930 Docs: fix the redirect in netlify.toml
  docs/website/netlify.toml
Labels: bug, documentation

#1903 Added info about backend kwargs in pyarrow
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
Labels: documentation

#1956 Fix for multiple ignores is not working
  dlt/sources/helpers/rest_client/client.py
  dlt/sources/rest_api/config_setup.py
  tests/sources/rest_api/configurations/test_response_actions_config.py
  tests/sources/rest_api/conftest.py
  tests/sources/rest_api/integration/test_offline.py
  tests/sources/rest_api/integration/test_response_actions.py
Labels: bug

#1936 Docs: sync styles with dlthub
  docs/website/docusaurus.config.js
  docs/website/src/css/custom.css
  docs/website/static/img/Customization-Active-1.svg
  docs/website/static/img/Customization-Inactive-1.svg
  docs/website/static/img/Destinations-Active-1.svg
  docs/website/static/img/Destinations-Inactive-1.svg
  docs/website/static/img/GeneralUsage-Active-1.svg
  docs/website/static/img/GeneralUsage-Inactive-1.svg
  docs/website/static/img/GettingStarted-Active-1.svg
  docs/website/static/img/GettingStarted-Inactive-1.svg
  docs/website/static/img/Howdltworks-Active-1.svg
  docs/website/static/img/Howdltworks-Inactive-1.svg
  docs/website/static/img/Installation-Active-1.svg
  docs/website/static/img/Installation-Inactive-1.svg
  docs/website/static/img/Introduction-Active-1.svg
  docs/website/static/img/Introduction-Inactive-1.svg
  docs/website/static/img/Pipelines-Active-1.svg
  docs/website/static/img/Pipelines-Inactive-1.svg
  docs/website/static/img/Reference-Active-1.svg
  docs/website/static/img/Reference-Inactive-1.svg
  docs/website/static/img/RunningInProduction-Active-1.svg
  docs/website/static/img/RunningInProduction-Inactive-1.svg
  docs/website/static/img/Sources-Active-1.svg
  docs/website/static/img/Sources-Inactive-1.svg
  docs/website/static/img/UserGuide-Active-1.svg
  docs/website/static/img/UserGuide-Inactive-1.svg
  docs/website/static/img/UsingLoadedData-Active-1.svg
  docs/website/static/img/UsingLoadedData-Inactive-1.svg
  docs/website/static/img/Walkthrough-Active-1.svg
  docs/website/static/img/Walkthrough-Inactive-1.svg
  docs/website/static/img/architecture-diagram.png
Labels: documentation

#1964 Docs: update the title in postgres.md
  docs/website/docs/dlt-ecosystem/destinations/postgres.md
Labels: documentation

#1967 Docs: styles: remove underline for cards in dark mode
  docs/website/src/css/custom.css
Labels: documentation

#1962 Docs: add a note to the Databricks docs
  docs/website/docs/dlt-ecosystem/destinations/databricks.md
Labels: documentation

#1773 Added info to troubleshooting
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/troubleshooting.md
Labels: documentation
