Repository dlt-hub/dlt, pull requests merged in 2024-08, with the labels that each got.

#1508 Updated credentials docs
  docs/examples/custom_destination_bigquery/custom_destination_bigquery.py
  docs/examples/google_sheets/google_sheets.py
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/general-usage/credentials/advanced.md
  docs/website/docs/general-usage/credentials/complex_types.md
  docs/website/docs/general-usage/credentials/config_providers.md
  docs/website/docs/general-usage/credentials/configuration.md
  docs/website/docs/general-usage/credentials/index.md
  docs/website/docs/general-usage/credentials/setup.md
  docs/website/docs/general-usage/destination.md
  docs/website/docs/general-usage/glossary.md
  docs/website/docs/running-in-production/running.md
  docs/website/docs/walkthroughs/add_credentials.md
  docs/website/docs/walkthroughs/create-a-pipeline.md
  docs/website/sidebars.js
Labels: documentation

#1664 Add `get_delta_tables` helper function
  dlt/common/libs/deltalake.py
  dlt/common/schema/schema.py
  dlt/destinations/impl/filesystem/factory.py
  dlt/destinations/impl/filesystem/filesystem.py
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  tests/libs/test_deltalake.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/pipeline/utils.py
Labels: enhancement

#1660 Updated the docs: Using pipeline.default_schema.toprettyyaml()
  docs/website/docs/general-usage/schema.md
Labels: documentation, community

#1686 Add `storage_options` to `DeltaTable.create`
  dlt/common/schema/exceptions.py
  dlt/common/schema/utils.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/normalize/schema.py
  tests/load/pipeline/test_filesystem_pipeline.py
Labels: bug

#1694 Docs: handle renamed credential docs pages
  docs/website/netlify.toml
Labels: bug

#1702 fixes load job counter
  dlt/common/runtime/collector.py
  dlt/load/load.py
Labels: bug

#1677 RESTClient: stops pagination after empty page (Feat/1637)
  dlt/sources/helpers/rest_client/client.py
  dlt/sources/helpers/rest_client/paginators.py
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/general-usage/http/rest-client.md
  tests/sources/helpers/rest_client/test_client.py
  tests/sources/helpers/rest_client/test_paginators.py
Labels: enhancement

#1662 Docs/issue 1661 add tip to source docs and update weaviate docs
  docs/website/docs/dlt-ecosystem/destinations/lancedb.md
  docs/website/docs/dlt-ecosystem/destinations/qdrant.md
  docs/website/docs/dlt-ecosystem/destinations/weaviate.md
  docs/website/docs/general-usage/source.md
Labels: documentation, community

#1678 Add custom parent-child relationships example
  docs/examples/parent_child_relationship/__init__.py
  docs/examples/parent_child_relationship/parent_child_relationship.py
  docs/examples/parent_child_relationship/test_parent_child_relationship.py
Labels: documentation, community

#1735 Replaced "full_refresh" with "dev_mode"
  docs/technical/general_usage.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
  docs/website/docs/dlt-ecosystem/verified-sources/stripe.md
  docs/website/docs/dlt-ecosystem/verified-sources/workable.md
Labels: documentation

#1740 Feat/1711 create with not exists dlt tables
  dlt/common/destination/capabilities.py
  dlt/common/destination/reference.py
  dlt/common/normalizers/json/relational.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/destinations/impl/mssql/factory.py
  dlt/destinations/impl/synapse/factory.py
  dlt/destinations/job_client_impl.py
  docs/examples/parent_child_relationship/parent_child_relationship.py
  docs/examples/parent_child_relationship/test_parent_child_relationship.py
  tests/load/mssql/test_mssql_table_builder.py
  tests/load/postgres/test_postgres_table_builder.py
  tests/pipeline/test_pipeline_trace.py
Labels: support

#1755 enables external location and named credential in databricks
  .github/workflows/test_destinations.yml
  dlt/common/configuration/specs/azure_credentials.py
  dlt/common/libs/deltalake.py
  dlt/common/metrics.py
  dlt/common/normalizers/json/__init__.py
  dlt/common/normalizers/json/relational.py
  dlt/common/storages/configuration.py
  dlt/common/storages/fsspec_filesystem.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/databricks/configuration.py
  dlt/destinations/impl/databricks/databricks.py
  dlt/destinations/impl/databricks/factory.py
  dlt/destinations/impl/dummy/dummy.py
  dlt/destinations/impl/filesystem/filesystem.py
  docs/website/docs/dlt-ecosystem/destinations/databricks.md
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
  docs/website/docs/running-in-production/running.md
  tests/.dlt/config.toml
  tests/common/cases/normalizers/sql_upper.py
  tests/common/storages/test_local_filesystem.py
  tests/destinations/test_destination_name_and_config.py
  tests/load/databricks/test_databricks_configuration.py
  tests/load/filesystem/test_filesystem_common.py
  tests/load/pipeline/test_databricks_pipeline.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/load/pipeline/test_stage_loading.py
  tests/load/test_dummy_client.py
  tests/load/utils.py
  tests/pipeline/cases/contracts/trace.schema.yaml
  tests/pipeline/test_pipeline.py
  tests/pipeline/test_pipeline_trace.py
Labels: support

#1576 Fix/1571 Incremental: Optionally load or ignore records with cursor_path missing or None value
  dlt/extract/incremental/__init__.py
  dlt/extract/incremental/exceptions.py
  dlt/extract/incremental/transform.py
  dlt/extract/incremental/typing.py
  docs/website/docs/general-usage/incremental-loading.md
  tests/extract/test_incremental.py
  tests/pipeline/test_pipeline_extra.py
Labels: community
