Repository dlt-hub/dlt, pull requests merged in 2024-11, with the labels that each got.

#2000 1990 - dataset columns select and limit
  .github/workflows/test_destinations.yml
  dlt/common/configuration/accessors.py
  dlt/common/destination/reference.py
  dlt/destinations/dataset.py
  dlt/destinations/impl/clickhouse/clickhouse.py
  dlt/destinations/impl/databricks/databricks.py
  dlt/destinations/impl/filesystem/sql_client.py
  dlt/destinations/impl/mssql/sql_client.py
  dlt/destinations/impl/redshift/redshift.py
  dlt/destinations/impl/sqlalchemy/db_api_client.py
  dlt/destinations/sql_client.py
  dlt/destinations/utils.py
  dlt/extract/source.py
  poetry.lock
  tests/destinations/test_readable_dbapi_dataset.py
  tests/load/filesystem/test_sql_client.py
  tests/load/pipeline/test_pipelines.py
  tests/load/test_read_interfaces.py
  tests/load/utils.py
Labels: destination

#1620 LanceDB - Remove Orphaned Chunks
  dlt/common/data_writers/escape.py
  dlt/destinations/impl/databricks/databricks.py
  dlt/destinations/impl/databricks/sql_client.py
  dlt/destinations/impl/lancedb/configuration.py
  dlt/destinations/impl/lancedb/factory.py
  dlt/destinations/impl/lancedb/lancedb_adapter.py
  dlt/destinations/impl/lancedb/lancedb_client.py
  dlt/destinations/impl/lancedb/schema.py
  dlt/destinations/impl/lancedb/utils.py
  dlt/destinations/impl/qdrant/qdrant_adapter.py
  dlt/destinations/impl/weaviate/weaviate_adapter.py
  dlt/destinations/sql_jobs.py
  docs/website/docs/dlt-ecosystem/destinations/lancedb.md
  poetry.lock
  pyproject.toml
  tests/load/lancedb/test_merge.py
  tests/load/lancedb/test_pipeline.py
  tests/load/lancedb/test_utils.py
  tests/load/lancedb/utils.py
  tests/load/utils.py
Labels: bug, destination

#1993 Added partial loading example
  .github/workflows/test_doc_snippets.yml
  docs/examples/partial_loading/.dlt/config.toml
  docs/examples/partial_loading/.dlt/example.secrets.toml
  docs/examples/partial_loading/__init__.py
  docs/examples/partial_loading/partial_loading.py
  docs/examples/partial_loading/requirements.txt
Labels: documentation

#1805 Added deploy with modal.
  Makefile
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-modal.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy_snippets/__init__.py
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy_snippets/deploy-with-modal-snippets.py
  docs/website/sidebars.js
  poetry.lock
  pyproject.toml
Labels: documentation

#2034 Updated google cloud function documentation
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-google-cloud-functions.md
Labels: documentation

#2026 fix resource level max_table_nesting and normalizer performance tuning
  dlt/common/normalizers/json/relational.py
  tests/common/normalizers/test_json_relational.py
  tests/normalize/test_max_nesting.py
Labels: bug

#2036 add warning for large delta memory footprint on filesystem docs page
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
Labels: documentation

#2038 Added docs on how to deploy a pipeline using Google Cloud run
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-google-cloud-run.md
  docs/website/sidebars.js
Labels: documentation

#2035 fix bigquery autodetect
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/bigquery/sql_client.py
  dlt/destinations/sql_jobs.py
  tests/load/pipeline/test_bigquery.py
Labels: bug

#2072 Updated sql_database documentation for resource usage
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
Labels: documentation

#2094 Updated Redshift documentation with a note on driver selection
  docs/website/docs/dlt-ecosystem/destinations/redshift.md
Labels: documentation

#2006 data access documentation
  docs/website/docs/dlt-ecosystem/visualizations/exploring-the-data.md
  docs/website/docs/general-usage/dataset-access/data-quality-dashboard.md
  docs/website/docs/general-usage/dataset-access/dataset.md
  docs/website/docs/general-usage/dataset-access/ibis-backend.md
  docs/website/docs/general-usage/dataset-access/index.md
  docs/website/docs/general-usage/dataset-access/sql-client.md
  docs/website/docs/general-usage/dataset-access/streamlit.md
  docs/website/docs/general-usage/destination-tables.md
  docs/website/docs/walkthroughs/adjust-a-schema.md
  docs/website/netlify.toml
  docs/website/sidebars.js
Labels: documentation

#2103 Fix minor typo :3
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
Labels: documentation

#1927 Support Spatial Types for PostGIS
  .github/workflows/test_dbt_runner.yml
  .github/workflows/test_destinations.yml
  .github/workflows/test_local_destinations.yml
  .github/workflows/test_local_sources.yml
  dlt/common/libs/pyarrow.py
  dlt/destinations/impl/postgres/factory.py
  dlt/destinations/impl/postgres/postgres.py
  dlt/destinations/impl/postgres/postgres_adapter.py
  docs/website/docs/dlt-ecosystem/destinations/postgres.md
  poetry.lock
  pyproject.toml
  tests/load/postgres/test_postgres_table_builder.py
  tests/load/postgres/utils.py
Labels: enhancement, destination, community
