Repository dlt-hub/dlt, pull requests merged in 2024-04, with the labels that each got.

#1086 Docs: Deploy dlt on dagster
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-dagster.md
  docs/website/sidebars.js
Labels: documentation

#1192 Add yaml representer for pendulum datetime
  dlt/helpers/streamlit_app/blocks/resource_state.py
Labels: bug

#1026 Add Dremio as a destination
  .github/workflows/test_destination_dremio.yml
  .github/workflows/test_local_destinations.yml
  dlt/common/data_writers/escape.py
  dlt/destinations/__init__.py
  dlt/destinations/impl/dremio/__init__.py
  dlt/destinations/impl/dremio/configuration.py
  dlt/destinations/impl/dremio/dremio.py
  dlt/destinations/impl/dremio/factory.py
  dlt/destinations/impl/dremio/pydremio.py
  dlt/destinations/impl/dremio/sql_client.py
  dlt/destinations/impl/mssql/mssql.py
  dlt/destinations/sql_jobs.py
  docs/website/docs/dlt-ecosystem/destinations/dremio.md
  docs/website/sidebars.js
  poetry.lock
  pyproject.toml
  tests/cases.py
  tests/cli/test_init_command.py
  tests/load/dremio/__init__.py
  tests/load/dremio/bootstrap/Dockerfile
  tests/load/dremio/bootstrap/bootstrap_dremio.sh
  tests/load/dremio/bootstrap/minio.json
  tests/load/dremio/bootstrap/nas.json
  tests/load/dremio/docker-compose.yml
  tests/load/dremio/test_dremio_client.py
  tests/load/pipeline/test_dremio.py
  tests/load/pipeline/test_merge_disposition.py
  tests/load/pipeline/test_pipelines.py
  tests/load/pipeline/test_stage_loading.py
  tests/load/pipeline/test_write_disposition_changes.py
  tests/load/test_job_client.py
  tests/load/test_sql_client.py
  tests/load/utils.py
  tests/utils.py
Labels: destination, community

#1166 Replaced broken links
  docs/website/blog/2023-06-10-schema-evolution.md
  docs/website/blog/2023-08-21-dlt-lineage-support.md
  docs/website/blog/2023-10-06-dlt-holistics.md
Labels: documentation

#1178 Updated schema docs for naming convention
  docs/website/docs/general-usage/schema.md
Labels: documentation

#1215 Docs: Corrected a snippet for naming = "direct"
  docs/website/docs/general-usage/schema.md
Labels: documentation

#1167 docs/updated synapse documentation
  docs/website/docs/dlt-ecosystem/destinations/synapse.md
Labels: documentation

#1138 Added docs for deploying dlt with Prefect.
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-prefect.md
  docs/website/sidebars.js
Labels: documentation

#1182 Extend layout placeholder params for filesystem destinations
  dlt/destinations/exceptions.py
  dlt/destinations/impl/dummy/dummy.py
  dlt/destinations/impl/filesystem/configuration.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/destinations/impl/filesystem/typing.py
  dlt/destinations/path_utils.py
  poetry.lock
  pyproject.toml
  tests/destinations/test_path_utils.py
  tests/load/filesystem/test_filesystem_client.py
  tests/load/filesystem/test_filesystem_common.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/load/test_dummy_client.py
Labels: enhancement, destination

#1191 add blog article shift left data democracy
  docs/website/blog/2024-04-05-governance-democracy-mesh.md
Labels: documentation

#1223 Update tzdata to 2024.1
  poetry.lock
  pyproject.toml
Labels: enhancement

#1230 fix athena iceberg's trailing location
  dlt/destinations/impl/athena/athena.py
Labels: ci from fork

#1238 Revert tzdata update and update lock
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
Labels: dependency update

#1245 Enable all tests always for biquery
  .github/workflows/test_destination_bigquery.yml
Labels: ci full

#1155 Check for default schema and schema name in streamlit session
  dlt/helpers/streamlit_app/blocks/load_info.py
  dlt/helpers/streamlit_app/blocks/resource_state.py
  dlt/helpers/streamlit_app/pages/dashboard.py
  dlt/helpers/streamlit_app/widgets/schema.py
  tests/helpers/streamlit_tests/test_streamlit_show_resources.py
Labels: bug, enhancement

#1260 Add seconds and millisecond timestamps to filesystem date placeholders
  dlt/destinations/path_utils.py
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  tests/destinations/test_path_utils.py
  tests/load/pipeline/test_filesystem_pipeline.py
Labels: enhancement

#1225 Make merge write-disposition fall back to append if no primary or merge keys are specified
  dlt/common/destination/reference.py
  dlt/destinations/sql_jobs.py
  docs/website/docs/general-usage/incremental-loading.md
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/load/pipeline/test_merge_disposition.py
  tests/load/pipeline/test_write_disposition_changes.py
  tests/load/utils.py
Labels: ci full

#1251 Docs: Updated SQL documentation for windows authentication.
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
  docs/website/package-lock.json
Labels: documentation

#1253 Docs: Updated autodetectors info
  docs/website/docs/general-usage/schema.md
Labels: documentation

#1242 Add max_table_nesting to resource decorator
  dlt/common/normalizers/json/relational.py
  dlt/extract/decorators.py
  dlt/extract/resource.py
  docs/website/docs/general-usage/resource.md
  tests/normalize/test_max_nesting.py
Labels: enhancement

#1275 `scd2` extension: active record literal changes
  dlt/common/schema/typing.py
  dlt/common/schema/utils.py
  dlt/destinations/sql_jobs.py
  dlt/extract/hints.py
  docs/website/docs/general-usage/incremental-loading.md
  tests/load/pipeline/test_scd2.py
Labels: enhancement

#1204 Docs/adding FAQ questions
  docs/website/docs/reference/frequently-asked-questions.md
  docs/website/sidebars.js
Labels: documentation

#1097 Clickhouse
  .github/workflows/test_destination_clickhouse.yml
  dlt/common/configuration/providers/airflow.py
  dlt/common/configuration/specs/base_configuration.py
  dlt/common/data_writers/escape.py
  dlt/common/destination/capabilities.py
  dlt/common/time.py
  dlt/destinations/__init__.py
  dlt/destinations/adapters.py
  dlt/destinations/impl/clickhouse/__init__.py
  dlt/destinations/impl/clickhouse/clickhouse.py
  dlt/destinations/impl/clickhouse/clickhouse_adapter.py
  dlt/destinations/impl/clickhouse/configuration.py
  dlt/destinations/impl/clickhouse/factory.py
  dlt/destinations/impl/clickhouse/sql_client.py
  dlt/destinations/impl/clickhouse/utils.py
  dlt/destinations/impl/databricks/sql_client.py
  dlt/destinations/impl/duckdb/sql_client.py
  dlt/destinations/impl/snowflake/sql_client.py
  dlt/destinations/sql_jobs.py
  dlt/destinations/utils.py
  dlt/helpers/dbt/profiles.yml
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
  docs/website/sidebars.js
  poetry.lock
  pyproject.toml
  tests/cases.py
  tests/load/clickhouse/__init__.py
  tests/load/clickhouse/test_clickhouse_adapter.py
  tests/load/clickhouse/test_clickhouse_configuration.py
  tests/load/clickhouse/test_clickhouse_table_builder.py
  tests/load/pipeline/test_arrow_loading.py
  tests/load/pipeline/test_clickhouse.py
  tests/load/pipeline/test_merge_disposition.py
  tests/load/pipeline/test_pipelines.py
  tests/load/pipeline/test_scd2.py
  tests/load/pipeline/test_stage_loading.py
  tests/load/pipeline/test_write_disposition_changes.py
  tests/load/test_job_client.py
  tests/load/test_sql_client.py
  tests/load/utils.py
  tests/utils.py
Labels: ci full

#1224 Docs: Google Ads documentation.
  docs/examples/google_sheets/google_sheets.py
  docs/website/docs/dlt-ecosystem/verified-sources/google_ads.md
  docs/website/sidebars.js
Labels: documentation

#1300 Do not show a notice if there is no resource state for schema
  dlt/helpers/streamlit_app/blocks/resource_state.py
Labels: enhancement
