Repository dlt-hub/dlt, pull requests merged in 2024-02, with the labels that each got.

#951 Handle UnionType when checking is_union_type and is_optional_type
  dlt/common/libs/pydantic.py
  dlt/common/typing.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/databricks/databricks.py
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/pipeline/pipeline.py
  tests/common/test_typing.py
  tests/libs/test_pydantic.py
Labels: bug, enhancement

#952 855 create bigquery adapter for dlt resources
  dlt/common/pendulum.py
  dlt/common/schema/utils.py
  dlt/common/validation.py
  dlt/destinations/adapters.py
  dlt/destinations/impl/bigquery/README.md
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/bigquery/bigquery_adapter.py
  dlt/destinations/impl/bigquery/configuration.py
  dlt/destinations/impl/bigquery/sql_client.py
  dlt/destinations/job_client_impl.py
  dlt/extract/hints.py
  docs/website/docs/dlt-ecosystem/destinations/bigquery.md
  poetry.lock
  tests/load/bigquery/test_bigquery_table_builder.py
  tests/load/qdrant/test_pipeline.py
  tests/load/utils.py
  tests/load/weaviate/test_pipeline.py
Labels: documentation, enhancement

#990 does not lowercase postgres and redshift database names
  dlt/destinations/impl/postgres/configuration.py
  tests/load/postgres/test_postgres_client.py
  tests/load/redshift/test_redshift_table_builder.py
Labels: bug

#993 Fix small typings in contributing guide
  .github/workflows/get_docs_changes.yml
  CONTRIBUTING.md
Labels: documentation
