Repository dlt-hub/dlt, pull requests merged in 2024-09, with the labels that each got.

#1771 Don't use Custom Embedding Functions
  dlt/destinations/impl/lancedb/configuration.py
  dlt/destinations/impl/lancedb/lancedb_client.py
  dlt/destinations/impl/lancedb/models.py
  docs/website/docs/dlt-ecosystem/destinations/lancedb.md
  poetry.lock
  pyproject.toml
  tests/load/lancedb/test_pipeline.py
  tests/load/lancedb/utils.py
Labels: bug, destination, community

#1779 sets default concurrency for blob upload for adlfs to 1
  dlt/common/storages/fsspec_filesystem.py
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
Labels: bug, support

#1770 historic docs v2
  docs/website/.gitignore
  docs/website/README.md
  docs/website/docusaurus.config.js
  docs/website/package-lock.json
  docs/website/package.json
  docs/website/sidebars.js
  docs/website/tools/clear_versions.js
  docs/website/tools/update_version_env.js
  docs/website/tools/update_versions.js
Labels: documentation, sprint

#1761 Docs/update deploy dagster
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-dagster.md
Labels: documentation

#1784 updated the documentation
  docs/website/docs/general-usage/incremental-loading.md
Labels: documentation

#1760 Refined documentation with minor improvements
  docs/examples/custom_destination_lancedb/custom_destination_lancedb.py
  docs/website/docs/general-usage/incremental-loading.md
Labels: documentation

#1758 Updated performance docs for parameters file_max_items & bytes
  docs/website/docs/reference/performance.md
Labels: documentation

#1782 controls row groups and empty tables
  dlt/common/data_writers/buffered.py
  dlt/common/data_writers/writers.py
  dlt/common/libs/pyarrow.py
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  tests/libs/test_parquet_writer.py
  tests/libs/test_pyarrow.py
Labels: bug

#1750 Move sources and destinations to the top level
  docs/website/docs/dlt-ecosystem/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem.md
  docs/website/docs/dlt-ecosystem/verified-sources/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
  docs/website/sidebars.js
  docs/website/src/css/custom.css
  docs/website/static/img/Sources-Active-1.svg
  docs/website/static/img/Sources-Active.svg
  docs/website/static/img/Sources-Inactive-1.svg
  docs/website/static/img/Sources-Inactive.svg
Labels: documentation, sprint

#1802 Docs: update the blog link in the docs' menu
  docs/website/docusaurus.config.js
Labels: documentation

#1745 Refactor filesystem doc
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/index.md
  docs/website/sidebars.js
Labels: documentation, sprint

#1623 structural and content changes to the sql_database doc
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/setup.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/troubleshooting.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/usage.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-airflow-composer.md
  docs/website/sidebars.js
Labels: documentation, sprint

#1803 skips tables without jobs when merging delta tables
  dlt/common/libs/deltalake.py
  dlt/destinations/impl/clickhouse/clickhouse.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/extract/hints.py
  tests/destinations/test_custom_destination.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/load/pipeline/test_merge_disposition.py
  tests/load/postgres/postgres/Dockerfile
Labels: sprint

#1775 Add filesystem tutorial
  docs/website/docs/tutorial/filesystem.md
  docs/website/sidebars.js
  docs/website/static/img/filesystem-tutorial/streamlit-data.png
  docs/website/static/img/filesystem-tutorial/streamlit-incremental-state.png
  docs/website/static/img/filesystem-tutorial/streamlit-new-col.png
Labels: documentation, sprint

#1535 creates a single source in extract for all resource instances passed as list
  dlt/common/utils.py
  dlt/extract/extract.py
  tests/common/test_utils.py
  tests/pipeline/test_pipeline.py
Labels: sprint

#1806 Enable BigQuery schema auto-detection with partitioning and clustering hints
  dlt/destinations/impl/bigquery/bigquery.py
  tests/load/bigquery/test_bigquery_table_builder.py
  tests/load/pipeline/test_bigquery.py
Labels: bug, destination

#1729 Docs: update the introduction, add the rest_api tutorial
  docs/website/docs/intro.md
  docs/website/docs/reference/installation.md
  docs/website/docs/tutorial/filesystem.md
  docs/website/docs/tutorial/grouping-resources.md
  docs/website/docs/tutorial/intro.md
  docs/website/docs/tutorial/load-data-from-an-api.md
  docs/website/docs/tutorial/rest-api.md
  docs/website/docs/tutorial/sql-database.md
  docs/website/sidebars.js
  docs/website/src/css/custom.css
Labels: documentation, sprint

#1787 Reorder sidebar
  docs/website/docs/reference/performance.md
  docs/website/docs/tutorial/load-data-from-an-api.md
  docs/website/docs/walkthroughs/share-a-dataset.md
  docs/website/sidebars.js
  docs/website/src/css/custom.css
Labels: documentation

#1834 docs: fix absolute links
  .github/workflows/test_doc_snippets.yml
  Makefile
  docs/website/docs/dlt-ecosystem/destinations/bigquery.md
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
  docs/website/docs/dlt-ecosystem/destinations/synapse.md
  docs/website/docs/dlt-ecosystem/transformations/dbt/dbt_cloud.md
  docs/website/docs/dlt-ecosystem/verified-sources/amazon_kinesis.md
  docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
  docs/website/docs/dlt-ecosystem/verified-sources/google_analytics.md
  docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
  docs/website/docs/dlt-ecosystem/verified-sources/jira.md
  docs/website/docs/dlt-ecosystem/verified-sources/matomo.md
  docs/website/docs/dlt-ecosystem/verified-sources/openapi-generator.md
  docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/usage.md
  docs/website/docs/dlt-ecosystem/verified-sources/workable.md
  docs/website/docs/general-usage/data-enrichments/url-parser-data-enrichment.md
  docs/website/docs/general-usage/data-enrichments/user_agent_device_data_enrichment.md
  docs/website/docs/general-usage/destination-tables.md
  docs/website/docs/general-usage/schema-evolution.md
  docs/website/docs/reference/telemetry.md
  docs/website/docs/tutorial/sql-database.md
  docs/website/docs/walkthroughs/create-a-pipeline.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-prefect.md
  docs/website/docs/walkthroughs/zendesk-weaviate.md
  docs/website/tools/preprocess_docs.js
Labels: documentation

#1850 Fix typo in rest_api ValueError message
  dlt/sources/rest_api/config_setup.py
Labels: bug

#1851 Fix/1849 Do Not Parse Ignored Empty Responses
  dlt/sources/rest_api/config_setup.py
  tests/sources/rest_api/conftest.py
  tests/sources/rest_api/integration/test_offline.py
Labels: bug

#1838 feat: filesystem delete old pipeline state files
  dlt/common/storages/configuration.py
  dlt/destinations/impl/filesystem/filesystem.py
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  tests/load/filesystem/test_filesystem_common.py
  tests/load/pipeline/test_filesystem_pipeline.py
Labels: breaking

#1864 docs: fixing grammar files 60-80
  docs/website/docs/dlt-ecosystem/file-formats/insert-format.md
  docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  docs/website/docs/dlt-ecosystem/verified-sources/_source-info-header.md
  docs/website/docs/dlt-ecosystem/verified-sources/amazon_kinesis.md
  docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
  docs/website/docs/dlt-ecosystem/verified-sources/github.md
  docs/website/docs/dlt-ecosystem/verified-sources/google_analytics.md
  docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
  docs/website/docs/dlt-ecosystem/verified-sources/inbox.md
  docs/website/docs/dlt-ecosystem/verified-sources/jira.md
  docs/website/docs/dlt-ecosystem/verified-sources/kafka.md
  docs/website/docs/dlt-ecosystem/verified-sources/matomo.md
  docs/website/docs/dlt-ecosystem/verified-sources/notion.md
  docs/website/docs/dlt-ecosystem/verified-sources/openapi-generator.md
  docs/website/docs/dlt-ecosystem/verified-sources/personio.md
  docs/website/docs/dlt-ecosystem/verified-sources/pipedrive.md
  docs/website/docs/dlt-ecosystem/verified-sources/scrapy.md
  docs/website/docs/dlt-ecosystem/verified-sources/slack.md
  docs/website/docs/dlt-ecosystem/verified-sources/stripe.md
Labels: documentation

#1872 Docs: rest_api: document `processing_steps`
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
Labels: documentation

#1818 incremental `scd2` with `merge_key`
  dlt/common/schema/typing.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/sql_jobs.py
  dlt/extract/hints.py
  docs/website/docs/general-usage/incremental-loading.md
  tests/common/test_validation.py
  tests/load/pipeline/test_scd2.py
Labels: enhancement
