Repository dlt-hub/dlt, pull requests merged in 2024-06, with the labels that each got.

#1423 1272 Support ClickHouse GCS S3 compatibility mode in filesystem destination
  dlt/destinations/impl/clickhouse/clickhouse.py
  dlt/destinations/impl/clickhouse/utils.py
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
  tests/load/clickhouse/test_clickhouse_gcs_s3_compatibility.py
  tests/load/utils.py
Labels: bug, documentation, destination

#1432 skips non resolvable fields from appearing in sample secrets.toml
  dlt/cli/config_toml_writer.py
  tests/cli/test_init_command.py
Labels: bug

#1442 RESTClient: add docs for `init_request`
  docs/website/docs/general-usage/http/rest-client.md
Labels: documentation

#1430 fixes config injection edge cases
  .github/workflows/test_destinations.yml
  dlt/cli/config_toml_writer.py
  dlt/common/configuration/accessors.py
  dlt/common/configuration/container.py
  dlt/common/configuration/inject.py
  dlt/common/configuration/providers/context.py
  dlt/common/configuration/resolve.py
  dlt/common/configuration/specs/base_configuration.py
  dlt/common/destination/reference.py
  dlt/common/libs/pydantic.py
  dlt/common/reflection/spec.py
  dlt/common/storages/live_schema_storage.py
  dlt/common/typing.py
  dlt/common/utils.py
  dlt/destinations/impl/destination/configuration.py
  dlt/extract/decorators.py
  dlt/extract/extract.py
  dlt/extract/hints.py
  dlt/extract/incremental/__init__.py
  dlt/extract/resource.py
  dlt/extract/source.py
  dlt/helpers/dbt/__init__.py
  dlt/helpers/dbt/configuration.py
  dlt/helpers/dbt/runner.py
  dlt/pipeline/__init__.py
  dlt/pipeline/dbt.py
  dlt/pipeline/pipeline.py
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
  tests/common/configuration/test_accessors.py
  tests/common/configuration/test_configuration.py
  tests/common/configuration/test_inject.py
  tests/common/configuration/test_toml_provider.py
  tests/common/storages/test_schema_storage.py
  tests/common/test_typing.py
  tests/common/test_utils.py
  tests/extract/test_decorators.py
  tests/extract/test_extract.py
  tests/extract/test_incremental.py
  tests/extract/test_sources.py
  tests/helpers/streamlit_tests/__init__.py
Labels: bug

#1382 Add Delta table support for `filesystem` destination
  .github/workflows/test_common.yml
  .github/workflows/test_destinations.yml
  .github/workflows/test_local_destinations.yml
  dlt/common/configuration/specs/aws_credentials.py
  dlt/common/configuration/specs/azure_credentials.py
  dlt/common/configuration/specs/base_configuration.py
  dlt/common/configuration/specs/gcp_credentials.py
  dlt/common/destination/capabilities.py
  dlt/common/destination/reference.py
  dlt/common/libs/deltalake.py
  dlt/common/libs/pyarrow.py
  dlt/common/libs/pydantic.py
  dlt/common/schema/typing.py
  dlt/common/storages/configuration.py
  dlt/common/storages/load_package.py
  dlt/destinations/impl/athena/__init__.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/dummy/dummy.py
  dlt/destinations/impl/filesystem/__init__.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/destinations/job_client_impl.py
  dlt/destinations/job_impl.py
  dlt/extract/hints.py
  dlt/load/load.py
  dlt/normalize/items_normalizers.py
  dlt/normalize/normalize.py
  dlt/pipeline/pipeline.py
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
  docs/website/docs/dlt-ecosystem/table-formats/delta.md
  docs/website/docs/dlt-ecosystem/table-formats/iceberg.md
  poetry.lock
  pyproject.toml
  tests/cases.py
  tests/common/configuration/test_annotation_future.py
  tests/libs/test_deltalake.py
  tests/libs/test_pydantic.py
  tests/load/filesystem/test_filesystem_client.py
  tests/load/filesystem/test_filesystem_common.py
  tests/load/filesystem/test_object_store_rs_credentials.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/pipeline/utils.py
Labels: enhancement

#1452 RESTClient: pass environment settings to `requests.Session.send`
  dlt/sources/helpers/rest_client/client.py
  tests/sources/helpers/rest_client/test_client.py
Labels: bug

#1459 Add a docstring to the `IncrementalTransform` class
  dlt/extract/incremental/transform.py
Labels: documentation

#1472 fix: service principal auth support for synapse copy job
  dlt/destinations/impl/synapse/synapse.py
  dlt/extract/incremental/transform.py
  tests/load/pipeline/test_synapse.py
Labels: bug

#1493 Docs: cover custom authentication, rework paginators section
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/general-usage/http/rest-client.md
Labels: documentation

#1505 Info on how to retrieve secrets using google secret manager
  docs/website/docs/dlt-ecosystem/destinations/snowflake.md
  docs/website/docs/walkthroughs/add_credentials.md
Labels: documentation

#1424 Fixes incorrect type check in the snippet
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database.md
Labels: bug, documentation

#1357 #1356 implements OAuth2 Two-legged flow
  dlt/sources/helpers/rest_client/auth.py
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api.md
  docs/website/docs/general-usage/http/rest-client.md
  tests/sources/helpers/rest_client/conftest.py
  tests/sources/helpers/rest_client/test_client.py
Labels: enhancement, ci from fork

#1500 Shorten the installation section in README
  README.md
  docs/website/docs/reference/installation.md
Labels: documentation

#1323 Add LanceDB custom destination example code
  docs/examples/custom_destination_lancedb/.dlt/config.toml
  docs/examples/custom_destination_lancedb/.dlt/example.secrets.toml
  docs/examples/custom_destination_lancedb/.gitignore
  docs/examples/custom_destination_lancedb/__init__.py
  docs/examples/custom_destination_lancedb/custom_destination_lancedb.py
  docs/tools/fix_grammar_gpt.py
  poetry.lock
  pyproject.toml
Labels: documentation, destination

#1499 fix: `Pipeline.sql_client` credentials forwarding
  dlt/pipeline/pipeline.py
Labels: bug

#1515 RESTClient: fix duplicate params in URL in JSONResponsePaginator
  dlt/sources/helpers/rest_client/paginators.py
  tests/sources/helpers/rest_client/test_paginators.py
Labels: bug

#1513 Docs: remove metrics resource from stripe
  docs/website/docs/dlt-ecosystem/verified-sources/stripe.md
Labels: documentation

#1375 LanceDB Destination
  .github/workflows/test_destination_lancedb.yml
  .github/workflows/test_doc_snippets.yml
  dlt/destinations/__init__.py
  dlt/destinations/adapters.py
  dlt/destinations/impl/lancedb/__init__.py
  dlt/destinations/impl/lancedb/configuration.py
  dlt/destinations/impl/lancedb/exceptions.py
  dlt/destinations/impl/lancedb/factory.py
  dlt/destinations/impl/lancedb/lancedb_adapter.py
  dlt/destinations/impl/lancedb/lancedb_client.py
  dlt/destinations/impl/lancedb/models.py
  dlt/destinations/impl/lancedb/schema.py
  dlt/destinations/impl/lancedb/utils.py
  docs/website/docs/dlt-ecosystem/destinations/lancedb.md
  docs/website/sidebars.js
  poetry.lock
  pyproject.toml
  tests/load/lancedb/__init__.py
  tests/load/lancedb/test_config.py
  tests/load/lancedb/test_pipeline.py
  tests/load/lancedb/utils.py
  tests/load/qdrant/test_pipeline.py
  tests/load/utils.py
  tests/utils.py
Labels: destination, community, sprint
