Repository dlt-hub/dlt, pull requests merged in 2025-03, with the labels that each got.

#2358 authorizes workflows to be run if label is assigned
  .github/workflows/test_dbt_cloud.yml
  .github/workflows/test_dbt_runner.yml
  .github/workflows/test_destination_athena.yml
  .github/workflows/test_destination_athena_iceberg.yml
  .github/workflows/test_destination_bigquery.yml
  .github/workflows/test_destination_clickhouse.yml
  .github/workflows/test_destination_databricks.yml
  .github/workflows/test_destination_dremio.yml
  .github/workflows/test_destination_lancedb.yml
  .github/workflows/test_destination_motherduck.yml
  .github/workflows/test_destination_mssql.yml
  .github/workflows/test_destination_qdrant.yml
  .github/workflows/test_destination_snowflake.yml
  .github/workflows/test_destination_synapse.yml
  .github/workflows/test_destinations.yml
  .github/workflows/test_doc_snippets.yml
Labels: ci from fork

#2286 feat: support encoding custom types in `json` modules
  dlt/common/json/__init__.py
  dlt/common/json/_orjson.py
  dlt/common/json/_simplejson.py
  docs/website/docs/reference/performance.md
  tests/common/test_json.py
  tests/pipeline/test_pipeline_extra.py
Labels: ci from fork

#2357 docs: plus: fix sample Claude config
  docs/website/docs/plus/features/ai.md
Labels: documentation

#2331 update docusaurus & other docs dependency updates
  dlt/common/storages/fsspecs/google_drive.py
  docs/examples/incremental_loading/incremental_loading.py
  docs/examples/transformers/transformers.py
  docs/website/clean_pydoc_sidebar.py
  docs/website/docs/_book-onboarding-call.md
  docs/website/docs/dlt-ecosystem/destinations/athena.md
  docs/website/docs/dlt-ecosystem/destinations/bigquery.md
  docs/website/docs/dlt-ecosystem/destinations/databricks.md
  docs/website/docs/dlt-ecosystem/destinations/delta-iceberg.md
  docs/website/docs/dlt-ecosystem/file-formats/_set_the_format.mdx
  docs/website/docs/dlt-ecosystem/staging.md
  docs/website/docs/dlt-ecosystem/verified-sources/arrow-pandas.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/github.md
  docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
  docs/website/docs/dlt-ecosystem/verified-sources/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/matomo.md
  docs/website/docs/dlt-ecosystem/verified-sources/openapi-generator.md
  docs/website/docs/dlt-ecosystem/verified-sources/personio.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/usage.md
  docs/website/docs/dlt-ecosystem/verified-sources/zendesk.md
  docs/website/docs/general-usage/credentials/advanced.md
  docs/website/docs/general-usage/credentials/setup.md
  docs/website/docs/general-usage/dataset-access/streamlit.md
  docs/website/docs/general-usage/destination.md
  docs/website/docs/general-usage/glossary.md
  docs/website/docs/general-usage/http/overview.md
  docs/website/docs/general-usage/http/rest-client.md
  docs/website/docs/general-usage/incremental-loading.md
  docs/website/docs/general-usage/naming-convention.md
  docs/website/docs/general-usage/resource.md
  docs/website/docs/general-usage/schema.md
  docs/website/docs/general-usage/source.md
  docs/website/docs/general-usage/state.md
  docs/website/docs/plus/ecosystem/delta.md
  docs/website/docs/plus/features/projects.md
  docs/website/docs/plus/features/transformations/setup.md
  docs/website/docs/plus/getting-started/tutorial.md
  docs/website/docs/reference/frequently-asked-questions.md
  docs/website/docs/reference/performance.md
  docs/website/docs/tutorial/filesystem.md
  docs/website/docs/tutorial/load-data-from-an-api.md
  docs/website/docs/tutorial/sql-database.md
  docs/website/docs/walkthroughs/add_credentials.md
  docs/website/docs/walkthroughs/adjust-a-schema.md
  docs/website/docs/walkthroughs/create-a-pipeline.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-airflow-composer.md
  docs/website/docs/walkthroughs/run-a-pipeline.md
  docs/website/docusaurus.config.js
  docs/website/package-lock.json
  docs/website/package.json
  docs/website/pydoc-markdown.yml
  docs/website/pydoc_markdown_dlt.py
  docs/website/sidebars.js
  docs/website/src/css/custom.css
  docs/website/tools/update_versions.js
Labels: documentation

#2337 Docs/dlt plus custom doc breadcrumbs
  docs/website/docs/_plus_admonition.md
  docs/website/docs/plus/core-concepts/cache.md
  docs/website/docs/plus/core-concepts/datasets.md
  docs/website/docs/plus/core-concepts/profiles.md
  docs/website/docs/plus/core-concepts/project.md
  docs/website/docs/plus/ecosystem/delta.md
  docs/website/docs/plus/ecosystem/iceberg.md
  docs/website/docs/plus/ecosystem/ms-sql.md
  docs/website/docs/plus/features/ai.md
  docs/website/docs/plus/features/data-access.md
  docs/website/docs/plus/features/projects.md
  docs/website/docs/plus/features/quality/data-quality.md
  docs/website/docs/plus/features/quality/tests.md
  docs/website/docs/plus/features/transformations/dbt-transformations.md
  docs/website/docs/plus/features/transformations/index.md
  docs/website/docs/plus/features/transformations/python-transformations.md
  docs/website/docs/plus/features/transformations/setup.md
  docs/website/docs/plus/getting-started/installation.md
  docs/website/docs/plus/getting-started/tutorial.md
  docs/website/docs/plus/intro.md
  docs/website/docs/plus/production/observability.md
  docs/website/docs/plus/production/runners.md
  docs/website/docs/plus/reference.md
  docs/website/docusaurus.config.js
  docs/website/src/theme/DLTExampleHeader.tsx
  docs/website/src/theme/DocBreadcrumbs/Items/Home/index.tsx
  docs/website/src/theme/DocBreadcrumbs/Items/Home/styles.module.css
  docs/website/src/theme/DocBreadcrumbs/index.tsx
  docs/website/src/theme/DocBreadcrumbs/styles.module.css
  docs/website/src/theme/Heading/index.js
  docs/website/src/theme/MDXComponents.js
  docs/website/src/theme/PlusAdmonition/index.js
  docs/website/static/img/dlt+_logo.png
Labels: documentation

#2379 docs: re-enable versions
  docs/website/docusaurus.config.js
  docs/website/tools/update_versions.js
Labels: documentation

#2391 master merge for 1.8.1 release
  dlt/common/configuration/providers/__init__.py
  dlt/common/configuration/specs/aws_credentials.py
  dlt/common/libs/pydantic.py
  dlt/destinations/dataset/__init__.py
  dlt/destinations/impl/filesystem/filesystem.py
  dlt/destinations/impl/filesystem/sql_client.py
  dlt/destinations/impl/synapse/configuration.py
  dlt/destinations/utils.py
  dlt/extract/reference.py
  dlt/extract/source.py
  dlt/extract/utils.py
  dlt/pipeline/pipeline.py
  dlt/sources/rest_api/__init__.py
  dlt/sources/rest_api/config_setup.py
  dlt/sources/rest_api/typing.py
  docs/website/docs/dlt-ecosystem/verified-sources/salesforce.md
  docs/website/docusaurus.config.js
  docs/website/tools/update_versions.js
  poetry.lock
  pyproject.toml
  tests/libs/test_pydantic.py
  tests/load/sources/rest_api/test_rest_api_source.py
  tests/sources/rest_api/configurations/test_resolve_config.py
  tests/sources/rest_api/integration/test_offline.py
  tests/sources/rest_api/test_rest_api_source.py
Labels: ci from fork, ci full

#2326 Added docs for data security and encryption
  docs/website/docs/dlt-ecosystem/transformations/encryption.md
  docs/website/sidebars.js
Labels: documentation

#2387 Updated the adjust a schema and sql configuration docs
  docs/website/docs/dlt-ecosystem/destinations/postgres.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
  docs/website/docs/walkthroughs/adjust-a-schema.md
Labels: documentation

#2417 un-deprecates force_iceberg on athena via new destination cap settings
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/athena/configuration.py
  dlt/destinations/impl/athena/factory.py
  docs/website/docs/dlt-ecosystem/destinations/athena.md
  tests/load/athena_iceberg/test_athena_iceberg.py
Labels: ci full

#2354 Fix #2342 - Snowflake S3 Stage
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/destinations/impl/snowflake/utils.py
  tests/load/pipeline/test_snowflake_pipeline.py
  tests/load/snowflake/conftest.py
  tests/load/snowflake/test_snowflake_configuration.py
  tests/load/snowflake/test_snowflake_utils.py
Labels: ci from fork, ci full

#2443 bumps dlt to 1.9.0
  pyproject.toml
Labels: ci from fork, ci full

#2446 feat(paginator): enhance JSONResponseCursorPaginator to support cursor placement in request JSON body
  dlt/sources/helpers/rest_client/paginators.py
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
  docs/website/docs/general-usage/http/rest-client.md
  tests/sources/helpers/rest_client/test_client.py
  tests/sources/helpers/rest_client/test_paginators.py
Labels: enhancement
