Repository dlt-hub/dlt, pull requests merged in 2025-05, with the labels that each got.

#2584 docs: marimo docs page added
  docs/website/docs/general-usage/dataset-access/marimo.md
  docs/website/docs/general-usage/dataset-access/static/marimo_dataset.png
  docs/website/docs/general-usage/dataset-access/static/marimo_notebook.png
  docs/website/docs/general-usage/dataset-access/static/marimo_python.png
  docs/website/docs/general-usage/dataset-access/static/marimo_sql.png
Labels: documentation

#2589 fix: update placeholder values in TOML writer tests
  tests/cli/test_config_toml_writer.py
Labels: bug, ci from fork

#2594 slightly clarify clickhouse docs
  dlt/destinations/impl/clickhouse/configuration.py
  docs/website/docs/dlt-ecosystem/destinations/clickhouse.md
Labels: documentation

#2465 Docs/changes to advanced tutorial
  docs/website/docs/plus/features/projects.md
  docs/website/docs/plus/getting-started/advanced_tutorial.md
Labels: documentation

#2583 fixes parquet data writer settings docs & rewrites configuration docs
  dlt/common/configuration/providers/doc.py
  dlt/common/configuration/specs/config_section_context.py
  dlt/common/pipeline.py
  dlt/common/schema/normalizers.py
  dlt/common/utils.py
  dlt/destinations/adapters.py
  dlt/extract/decorators.py
  dlt/extract/extract.py
  dlt/extract/resource.py
  dlt/extract/utils.py
  dlt/helpers/ibis.py
  dlt/pipeline/pipeline.py
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  docs/website/docs/dlt-ecosystem/verified-sources/filesystem/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/index.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/setup.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/usage.md
  docs/website/docs/general-usage/credentials/advanced.md
  docs/website/docs/general-usage/credentials/complex_types.md
  docs/website/docs/general-usage/credentials/index.md
  docs/website/docs/general-usage/credentials/setup.md
  docs/website/docs/general-usage/dataset-access/dataset.md
  docs/website/docs/general-usage/dataset-access/dataset_snippets/dataset_snippets.py
  docs/website/docs/general-usage/dataset-access/ibis-backend.md
  docs/website/docs/general-usage/dataset-access/index.md
  docs/website/docs/general-usage/dataset-access/marimo.md
  docs/website/docs/general-usage/dataset-access/sql-client.md
  docs/website/docs/general-usage/dataset-access/streamlit.md
  docs/website/docs/general-usage/destination-tables.md
  docs/website/docs/general-usage/destination.md
  docs/website/docs/general-usage/pipeline.md
  docs/website/docs/general-usage/schema-contracts.md
  docs/website/docs/general-usage/schema-evolution.md
  docs/website/docs/plus/features/ai.md
  docs/website/docs/plus/features/projects.md
  docs/website/docs/reference/performance.md
  docs/website/docs/reference/performance_snippets/.dlt/config.toml
  docs/website/docs/reference/performance_snippets/toml-snippets.toml
  docs/website/docs/tutorial/filesystem.md
  docs/website/docs/tutorial/sql-database.md
  docs/website/docs/walkthroughs/add-incremental-configuration.md
  docs/website/docs/walkthroughs/add_credentials.md
  docs/website/docs/walkthroughs/run-a-pipeline.md
  docs/website/sidebars.js
  tests/extract/test_decorators.py
  tests/extract/test_sources.py
  tests/load/test_read_interfaces.py
  tests/pipeline/test_arrow_sources.py
  tests/pipeline/test_pipeline.py
  tests/pipeline/test_pipeline_state.py
Labels: bug, documentation

#2235 Added dedup sort example
  docs/website/docs/general-usage/incremental-loading.md
Labels: documentation

#2338 docs: add advanced project tutorial
  docs/website/docs/plus/features/projects.md
  docs/website/docs/plus/getting-started/advanced_tutorial.md
  docs/website/docs/plus/getting-started/tutorial.md
  docs/website/sidebars.js
Labels: documentation

#2592 docs: split incremental loading page
  docs/examples/incremental_loading/incremental_loading.py
  docs/website/docs/dlt-ecosystem/destinations/delta-iceberg.md
  docs/website/docs/dlt-ecosystem/staging.md
  docs/website/docs/dlt-ecosystem/verified-sources/github.md
  docs/website/docs/dlt-ecosystem/verified-sources/google_sheets.md
  docs/website/docs/dlt-ecosystem/verified-sources/personio.md
  docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
  docs/website/docs/dlt-ecosystem/verified-sources/slack.md
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/usage.md
  docs/website/docs/general-usage/incremental-loading.md
  docs/website/docs/general-usage/incremental/advanced-state.md
  docs/website/docs/general-usage/incremental/cursor.md
  docs/website/docs/general-usage/incremental/lag.md
  docs/website/docs/general-usage/incremental/troubleshooting.md
  docs/website/docs/general-usage/merge-loading.md
  docs/website/docs/general-usage/naming-convention.md
  docs/website/docs/general-usage/pipeline.md
  docs/website/docs/general-usage/resource.md
  docs/website/docs/general-usage/schema.md
  docs/website/docs/general-usage/state.md
  docs/website/docs/plus/ecosystem/delta.md
  docs/website/docs/reference/explainers/how-dlt-works.md
  docs/website/docs/reference/frequently-asked-questions.md
  docs/website/docs/tutorial/load-data-from-an-api.md
  docs/website/sidebars.js
Labels: documentation

#2525 Added info about dlt's internal tables
  docs/website/docs/general-usage/destination-tables.md
Labels: documentation

#2535 Added section using xmin for Change Data Capture (CDC) to pg_replication docs
  docs/website/docs/dlt-ecosystem/verified-sources/pg_replication.md
Labels: documentation

#2500 Added Transform data with add_map documentation
  docs/website/docs/dlt-ecosystem/transformations/add-map.md
  docs/website/docs/dlt-ecosystem/transformations/dbt/dbt.md
  docs/website/docs/dlt-ecosystem/transformations/dbt/dbt_cloud.md
  docs/website/docs/dlt-ecosystem/transformations/python.md
  docs/website/docs/dlt-ecosystem/transformations/sql.md
  docs/website/sidebars.js
Labels: documentation

#2643 cli: fix 404 in the "ai" command output
  dlt/cli/ai_command.py
Labels: bug

#2634 fixes fsspec instantiation in fs source
  dlt/common/configuration/providers/vault.py
  dlt/common/storages/configuration.py
  dlt/common/storages/fsspec_filesystem.py
  dlt/normalize/items_normalizers.py
  dlt/pipeline/pipeline.py
  dlt/sources/filesystem/__init__.py
  dlt/sources/filesystem/helpers.py
  pyproject.toml
  tests/common/storages/utils.py
  tests/load/pipeline/test_filesystem_pipeline.py
  tests/load/pipeline/test_restore_state.py
  tests/load/sources/filesystem/test_filesystem_source.py
  tests/load/test_job_client.py
  tests/load/test_read_interfaces.py
  tests/load/utils.py
Labels: ci from fork, ci full

#2507 Normalize model files
  dlt/common/data_writers/writers.py
  dlt/common/utils.py
  dlt/destinations/job_client_impl.py
  dlt/extract/hints.py
  dlt/normalize/configuration.py
  dlt/normalize/items_normalizers.py
  dlt/normalize/worker.py
  tests/load/pipeline/test_model_item_format.py
  tests/normalize/test_model_item_normalizer.py
Labels: enhancement

#2600 2529-INFO_TABLES_QUERY_THRESHOLD-as-paramterer-from-config
  dlt/common/destination/client.py
  dlt/destinations/impl/athena/configuration.py
  dlt/destinations/job_client_impl.py
  docs/website/docs/dlt-ecosystem/destinations/athena.md
  tests/load/pipeline/test_pipelines.py
Labels: ci from fork

#2640 Feat: Add configuration propagation to deltalake.write_deltalake (#2629)
  dlt/common/libs/deltalake.py
  dlt/common/storages/configuration.py
  dlt/common/typing.py
  dlt/destinations/impl/filesystem/filesystem.py
  docs/website/docs/dlt-ecosystem/destinations/delta-iceberg.md
  docs/website/docs/plus/ecosystem/delta.md
  tests/libs/test_deltalake.py
  tests/load/filesystem/test_filesystem_common.py
Labels: ci from fork

#2645 Prevent unecessary preliminary connection in dataset
  dlt/destinations/dataset/dataset.py
  dlt/destinations/dataset/relation.py
  docs/website/docs/general-usage/dataset-access/dataset.md
  docs/website/docs/general-usage/dataset-access/dataset_snippets/dataset_snippets.py
  tests/load/test_read_interfaces.py
Labels: bug

#2663 Simplify workflow files
  .github/workflows/test_common.yml
  .github/workflows/test_dbt_runner.yml
  .github/workflows/test_destination_dremio.yml
Labels: tech-debt

#2678 fix/2677: remove recursive filewatching
  docs/website/tools/preprocess_docs.js
Labels: bug, documentation

#2630 QoL: improved `__repr__()` for public interface
  dlt/common/configuration/accessors.py
  dlt/common/configuration/providers/provider.py
  dlt/common/destination/reference.py
  dlt/common/schema/schema.py
  dlt/common/utils.py
  dlt/extract/resource.py
  dlt/extract/source.py
  dlt/pipeline/pipeline.py
  tests/common/configuration/test_accessors.py
  tests/common/configuration/test_providers.py
  tests/common/destination/test_reference.py
  tests/common/schema/test_schema.py
  tests/common/test_utils.py
  tests/extract/test_sources.py
  tests/pipeline/test_pipeline.py
Labels: QoL
