Repository dlt-hub/dlt, pull requests merged in 2025-08, with the labels that each got.

#2936 fix: restclient: handle null data in response
  dlt/sources/helpers/rest_client/client.py
  tests/sources/helpers/rest_client/test_client.py
  tests/sources/rest_api/conftest.py
Labels: bug

#2953 fix: prevent DuplicateSchema error when using public schema in Redshift
  dlt/destinations/impl/redshift/redshift.py
  tests/load/redshift/test_redshift_client.py
Labels: ci from fork

#2929 feat: `Schema.to_dbml()`
  dlt/cli/command_wrappers.py
  dlt/cli/pipeline_command.py
  dlt/cli/plugins.py
  dlt/common/schema/schema.py
  dlt/common/schema/utils.py
  dlt/common/storages/configuration.py
  dlt/common/storages/schema_storage.py
  dlt/helpers/dbml.py
  docs/tools/check_embedded_snippets.py
  docs/website/docs/general-usage/dataset-access/view-dlt-schema.md
  docs/website/docs/reference/command-line-interface.md
  docs/website/docs/walkthroughs/adjust-a-schema.md
  docs/website/sidebars.js
  pyproject.toml
  tests/helpers/test_dbml.py
  uv.lock
Labels: enhancement, release-highlight

#2958 bumps to version 1.15.0
  dlt/destinations/impl/filesystem/sql_client.py
  docs/website/docs/dlt-ecosystem/destinations/duckdb.md
  pyproject.toml
  tests/helpers/dbt_tests/test_runner_dbt_versions.py
  uv.lock
Labels: ci full

#2977 fix: `MissingDependencyException` should inherit `ImportError`
  dlt/common/exceptions.py
  dlt/common/reflection/ref.py
Labels: tech-debt, QoL

#2967 repo: use `ruff check` for linting
  Makefile
  dlt/helpers/dashboard/dlt_dashboard.py
  pyproject.toml
Labels: QoL
