Repository dlt-hub/dlt, pull requests merged in 2025-06, with the labels that each got.

#2633 QoL: warning with hint to provide data types for columns with exclusively None values
  dlt/common/destination/utils.py
  dlt/common/libs/pyarrow.py
  dlt/common/schema/exceptions.py
  dlt/common/schema/schema.py
  dlt/common/schema/typing.py
  dlt/common/schema/utils.py
  dlt/common/storages/schema_storage.py
  dlt/extract/extractors.py
  dlt/helpers/ibis.py
  dlt/normalize/items_normalizers.py
  dlt/normalize/normalize.py
  dlt/normalize/validate.py
  tests/common/schema/test_inference.py
  tests/common/schema/test_merges.py
  tests/libs/pyarrow/test_pyarrow.py
  tests/load/pipeline/test_arrow_loading.py
  tests/load/pipeline/test_merge_disposition.py
  tests/load/sources/sql_database/sql_source.py
  tests/load/sources/sql_database/test_sql_database_source.py
  tests/normalize/test_normalize.py
  tests/pipeline/cases/contracts/trace.schema.yaml
  tests/pipeline/test_arrow_sources.py
  tests/sources/sql_database/test_arrow_helpers.py
Labels: QoL

#2708 Feat/add athena dabatase location option
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/athena/configuration.py
  docs/website/docs/dlt-ecosystem/destinations/athena.md
Labels: ci from fork

#2756 mssql and snowflake bugfixes + bumps to 1.12.0
  .github/workflows/test_destinations_remote.yml
  dlt/cli/pipeline_command.py
  dlt/common/libs/deltalake.py
  dlt/common/schema/typing.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/duckdb/sql_client.py
  dlt/destinations/impl/mssql/factory.py
  dlt/destinations/impl/mssql/sql_client.py
  dlt/destinations/impl/snowflake/snowflake.py
  dlt/destinations/impl/sqlalchemy/merge_job.py
  dlt/destinations/impl/synapse/factory.py
  dlt/destinations/sql_jobs.py
  dlt/destinations/utils.py
  dlt/extract/hints.py
  docs/website/docs/dlt-ecosystem/destinations/mssql.md
  docs/website/docs/general-usage/merge-loading.md
  poetry.lock
  pyproject.toml
  tests/common/test_validation.py
  tests/helpers/dbt_tests/test_runner_dbt_versions.py
  tests/load/clickhouse/test_clickhouse_configuration.py
  tests/load/filesystem/test_aws_credentials.py
  tests/load/filesystem/test_azure_credentials.py
  tests/load/filesystem/test_credentials_mixins.py
  tests/load/filesystem/test_filesystem_client.py
  tests/load/filesystem/test_gcs_credentials.py
  tests/load/filesystem/test_pyiceberg_credentials.py
  tests/load/filesystem/utils.py
  tests/load/mssql/test_mssql_extras.py
  tests/load/pipeline/test_arrow_loading.py
  tests/load/pipeline/test_merge_disposition.py
  tests/load/pipeline/test_model_item_format.py
  tests/load/pipeline/test_pipelines.py
  tests/load/pipeline/test_refresh_modes.py
  tests/load/pipeline/test_replace_disposition.py
  tests/load/pipeline/test_restore_state.py
  tests/load/pipeline/test_snowflake_pipeline.py
  tests/load/pipeline/test_stage_loading.py
  tests/load/test_sql_client.py
Labels: ci full

#2796 (QoL):adds `str` and `repr` to dataset and relation
  dlt/common/configuration/specs/base_configuration.py
  dlt/common/destination/dataset.py
  dlt/common/destination/reference.py
  dlt/destinations/dataset/dataset.py
  dlt/destinations/dataset/relation.py
  dlt/destinations/job_client_impl.py
  tests/destinations/test_readable_dbapi_dataset.py
  tests/load/test_read_interfaces.py
Labels: QoL

#2797 fix: added `@dlt.transformation` to `__all__`
  dlt/__init__.py
Labels: QoL

#2682 Docs: updated on API rate-limit handling & incremental cursor errors
  docs/website/docs/general-usage/http/requests.md
  docs/website/docs/general-usage/incremental/troubleshooting.md
  docs/website/docs/general-usage/schema-evolution.md
  docs/website/docs/walkthroughs/deploy-a-pipeline/deploy-with-dagster.md
Labels: documentation

#2808 feat(athena): apply lakeformation tags on database (cont.)
  dlt/common/configuration/specs/aws_credentials.py
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/athena/configuration.py
  dlt/destinations/impl/athena/sql_client.py
  docs/website/docs/dlt-ecosystem/destinations/athena.md
  pyproject.toml
  tests/load/athena_iceberg/test_lakeformation.py
  uv.lock
Labels: ci full

#2810 Extend CSV quoting options in CsvWriter
  dlt/common/data_writers/configuration.py
  dlt/common/data_writers/writers.py
  docs/website/docs/dlt-ecosystem/file-formats/csv.md
  docs/website/docs/dlt-ecosystem/file-formats/insert-format.md
  docs/website/docs/dlt-ecosystem/file-formats/jsonl.md
  docs/website/docs/dlt-ecosystem/file-formats/parquet.md
  tests/libs/test_csv_writer.py
Labels: enhancement

#2747 docs: add docs for headers configuration
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/advanced.md
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
  tests/sources/rest_api/integration/test_offline.py
Labels: documentation
