Repository dlt-hub/dlt, pull requests merged in 2025-04, with the labels that each got.

#2462 rest_api: enhance placeholder expansion to preserve value types
  dlt/sources/rest_api/__init__.py
  dlt/sources/rest_api/config_setup.py
  tests/sources/rest_api/configurations/test_resolve_config.py
  tests/sources/rest_api/integration/test_offline.py
  tests/sources/rest_api/test_interpolation.py
Labels: bug

#2463 docs: MCP installation docs page
  docs/website/docs/dlt-ecosystem/llm-tooling/mcp-server.md
  docs/website/sidebars.js
Labels: documentation

#2441 list-destination flag added
  dlt/cli/command_wrappers.py
  dlt/cli/init_command.py
  dlt/cli/plugins.py
  docs/website/docs/reference/command-line-interface.md
  tests/cli/test_init_command.py
Labels: ci from fork

#2455 add ignore_unknown_values option to BigQuery destination
  dlt/destinations/impl/bigquery/bigquery.py
  dlt/destinations/impl/bigquery/configuration.py
  docs/website/docs/dlt-ecosystem/destinations/bigquery.md
  tests/load/bigquery/test_bigquery_client.py
Labels: ci from fork

#2435 Fix: insert-from-staging replace strategy incorrectly using staging-optimized pattern
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/mssql/mssql.py
  dlt/destinations/impl/postgres/postgres.py
  dlt/destinations/impl/sqlalchemy/load_jobs.py
  dlt/destinations/job_client_impl.py
  dlt/destinations/sql_jobs.py
  tests/load/pipeline/test_replace_disposition.py
Labels: ci from fork

#2453 Added info about additional permissions to iceberg docs
  docs/website/docs/dlt-ecosystem/destinations/delta-iceberg.md
Labels: documentation

#2491 fix: index invariant add_row_hash_to_table
  dlt/sources/helpers/transform.py
  tests/sources/helpers/transform/test_row_hash.py
Labels: ci from fork

#2361 adds condition to check XDG_DATA_HOME to set global_dir value
  dlt/common/runtime/run_context.py
  tests/common/runtime/test_run_context.py
Labels: ci from fork

#2494 docs: plus: snowflake_plus: added details on `catalog_sync`
  docs/website/docs/plus/ecosystem/snowflake_plus.md
Labels: documentation

#2474 docs: update incremental loading section in REST API documentation
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
Labels: documentation

#2511 Preserve type of emtpy lists in incremental to allow to materialize empty resources
  dlt/extract/incremental/__init__.py
  dlt/extract/items_transform.py
  tests/extract/test_extract.py
Labels: bug

#2510 Fix clickhouse sql syntax for sentinel table creation
  dlt/destinations/impl/clickhouse/sql_client.py
Labels: bug

#2517 [WIP]Docs for building Rest API with cursor
  docs/website/docs/dlt-ecosystem/llm-tooling/cursor-restapi.md
  docs/website/sidebars.js
Labels: documentation

#2524 docs: snowflake_plus: document `iceberg_mode` and `base_location` templating
  docs/website/docs/plus/ecosystem/snowflake_plus.md
Labels: documentation, enhancement

#2555 feat: adds iceberg table properties configuration for athena (#2546)
  dlt/destinations/impl/athena/athena.py
  dlt/destinations/impl/athena/configuration.py
  docs/website/docs/dlt-ecosystem/destinations/athena.md
Labels: ci from fork

#2514 use pendulum.parse instead of fromisoformat when deserializing pua json
  dlt/common/json/__init__.py
  tests/common/test_json.py
  tests/extract/test_incremental.py
Labels: bug

#2520 add basic docstring linting
  .github/workflows/test_doc_snippets.yml
  Makefile
  dlt/common/destination/dataset.py
  dlt/common/pipeline.py
  dlt/destinations/decorators.py
  dlt/destinations/impl/athena/factory.py
  dlt/destinations/impl/bigquery/factory.py
  dlt/destinations/impl/clickhouse/factory.py
  dlt/destinations/impl/databricks/factory.py
  dlt/destinations/impl/destination/factory.py
  dlt/destinations/impl/dremio/factory.py
  dlt/destinations/impl/duckdb/factory.py
  dlt/destinations/impl/dummy/factory.py
  dlt/destinations/impl/filesystem/factory.py
  dlt/destinations/impl/lancedb/factory.py
  dlt/destinations/impl/motherduck/factory.py
  dlt/destinations/impl/mssql/factory.py
  dlt/destinations/impl/postgres/factory.py
  dlt/destinations/impl/qdrant/factory.py
  dlt/destinations/impl/redshift/factory.py
  dlt/destinations/impl/snowflake/factory.py
  dlt/destinations/impl/sqlalchemy/factory.py
  dlt/destinations/impl/synapse/factory.py
  dlt/destinations/impl/weaviate/factory.py
  dlt/extract/decorators.py
  dlt/extract/source.py
  dlt/pipeline/__init__.py
  dlt/pipeline/pipeline.py
  dlt/sources/filesystem/__init__.py
  dlt/sources/sql_database/__init__.py
  docs/website/pydoc-markdown.yml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: documentation, tech-debt

#2552 Docs: add documentation for CT columns
  docs/website/docs/plus/ecosystem/ms-sql.md
Labels: documentation

#2581 Speedup CI: Cache google secrets
  tests/conftest.py
  tests/helpers/providers/test_google_secrets_provider.py
Labels: enhancement
