Repository dlt-hub/dlt, pull requests merged in 2025-09, with the labels that each got.

#3059 feat(dataset): simplify public interface for `dlt.Dataset` and `dlt.Relation`
  dlt/__init__.py
  dlt/common/data_writers/writers.py
  dlt/common/destination/capabilities.py
  dlt/common/destination/dataset.py
  dlt/common/libs/utils.py
  dlt/dataset/dataset.py
  dlt/dataset/lineage.py
  dlt/dataset/relation.py
  dlt/destinations/queries.py
  dlt/destinations/sql_client.py
  dlt/extract/hints.py
  dlt/helpers/dashboard/dlt_dashboard.py
  dlt/helpers/dashboard/utils.py
  dlt/normalize/items_normalizers.py
  dlt/pipeline/pipeline.py
  docs/website/docs/general-usage/dataset-access/dataset_snippets/dataset_snippets.py
  docs/website/docs/general-usage/transformations/transformation-snippets.py
  tests/destinations/test_queries.py
  tests/destinations/test_readable_dbapi_dataset.py
  tests/libs/test_utils.py
  tests/load/pipeline/test_duckdb.py
  tests/load/pipeline/test_open_tables.py
  tests/load/pipeline/test_snowflake_pipeline.py
  tests/load/test_read_interfaces.py
  tests/pipeline/utils.py
Labels: tech-debt, QoL

#3071 bumps to version 1.16
  pyproject.toml
  uv.lock
Labels: ci full

#3084 Add redirect from dlt-plus page
  docs/website/netlify.toml
Labels: documentation

#3138 docs: rest_api: fix rest_api_source parameters
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/advanced.md
Labels: bug, documentation

#3148 fix: explicitly replace `postgresql` by `postgres` in `ATTACH`
  dlt/destinations/impl/ducklake/sql_client.py
  tests/load/ducklake/test_ducklake_client.py
Labels: bug

#3150 fix: 3139 pass SQLAlchemy credentials to f-string
  dlt/destinations/impl/ducklake/ducklake.py
  dlt/destinations/impl/ducklake/sql_client.py
  tests/load/ducklake/test_ducklake_client.py
  tests/load/ducklake/test_ducklake_pipeline.py
Labels: bug

#3149 fix: 3145 add `read_parquet(use_arrow: bool)`
  dlt/common/storages/fsspec_filesystem.py
  dlt/sources/filesystem/readers.py
  tests/sources/filesystem/test_readers.py
Labels: enhancement, release-highlight
