Repository dlt-hub/dlt, pull requests merged in 2025-02, with the labels that each got.

#2255 docs: Fix typo in file name in "Create a pipeline" walkthrough
  docs/website/docs/walkthroughs/create-a-pipeline.md
Labels: bug, documentation

#2256 bumps dlt to 1.6.0
  pyproject.toml
Labels: ci full

#2297 docs: dlt+: add plus icon to sidebar
  docs/website/src/css/custom.css
  docs/website/static/img/Plus-Active-1.svg
  docs/website/static/img/Plus-Active.svg
  docs/website/static/img/Plus-Inactive-1.svg
  docs/website/static/img/Plus-Inactive.svg
Labels: documentation

#2291 Update dlt+ installation page
  docs/website/docs/plus/getting-started/installation.md
Labels: documentation

#2288 Add the base dlt-plus tutorial
  docs/website/docs/plus/core-concepts/profiles.md
  docs/website/docs/plus/core-concepts/project.md
  docs/website/docs/plus/features/projects.md
  docs/website/docs/plus/getting-started/advanced_tutorial.md
  docs/website/docs/plus/getting-started/tutorial.md
  docs/website/docs/plus/reference.md
  docs/website/sidebars.js
Labels: documentation

#2292 Delta & Iceberg docs in dlt+
  docs/website/docs/plus/ecosystem/delta.md
  docs/website/docs/plus/ecosystem/iceberg.md
  docs/website/docs/plus/ecosystem/ms-sql.md
Labels: documentation

#2300 Update MS SQL Change Tracking docs
  docs/website/docs/plus/ecosystem/ms-sql.md
Labels: documentation

#2281 feat: adding HeaderCursorPaginator
  dlt/sources/helpers/rest_client/paginators.py
  tests/sources/helpers/rest_client/test_paginators.py
  tests/sources/rest_api/conftest.py
Labels: enhancement

#2247 Updated performance docs for setting dlt data dir
  docs/website/docs/reference/performance.md
Labels: documentation

#2302 adding feature secure data access and sharing
  docs/website/docs/plus/features/data-access.md
  docs/website/docs/plus/features/security.md
  docs/website/sidebars.js
Labels: documentation

#2293 Add transformations feature
  docs/website/docs/plus/core-concepts/transformations.md
  docs/website/docs/plus/features/transformations.md
  docs/website/docs/plus/features/transformations/dbt-transformations.md
  docs/website/docs/plus/features/transformations/index.md
  docs/website/docs/plus/features/transformations/python-transformations.md
  docs/website/docs/plus/features/transformations/setup.md
  docs/website/sidebars.js
Labels: documentation

#2318 Add open source dlt+ references
  docs/website/docs/dlt-ecosystem/destinations/delta-iceberg.md
  docs/website/docs/plus/ecosystem/iceberg.md
Labels: documentation

#2301 modifying core-concepts and adding feature: projects
  docs/website/docs/plus/core-concepts/cache.md
  docs/website/docs/plus/core-concepts/datasets.md
  docs/website/docs/plus/core-concepts/project.md
  docs/website/docs/plus/features/projects.md
  docs/website/sidebars.js
Labels: documentation

#2327 [docs] adds corrections dlt plus docs
  docs/website/docs/plus/core-concepts/cache.md
  docs/website/docs/plus/core-concepts/datasets.md
  docs/website/docs/plus/core-concepts/profiles.md
  docs/website/docs/plus/core-concepts/project.md
  docs/website/docs/plus/features/ai.md
  docs/website/docs/plus/features/projects.md
  docs/website/docs/plus/features/quality/tests.md
  docs/website/docs/plus/getting-started/tutorial.md
Labels: documentation

#2330 small improvements to cli docs generator
  dlt/cli/docs_command.py
Labels: documentation

#2324 Docs: remove comments from the shell code blocks
  docs/website/docs/reference/installation.md
Labels: documentation

#2243 Updated sql database docs for selecting tables and columns via config.toml
  docs/website/docs/dlt-ecosystem/verified-sources/sql_database/configuration.md
Labels: documentation
