Repository dlt-hub/dlt, pull requests merged in 2025-07, with the labels that each got.

#2871 Added troubleshooting steps for Databricks and other minor updates
  docs/website/docs/dlt-ecosystem/destinations/databricks.md
  docs/website/docs/dlt-ecosystem/destinations/filesystem.md
Labels: documentation

#2889 bumps dlt to version 1.14.0
  pyproject.toml
  uv.lock
Labels: ci full

#2674 [Databricks destination] Adding comment and tags for table and columns and applying primary and foreign key constraints in Unity Catalog
  dlt/destinations/adapters.py
  dlt/destinations/impl/databricks/configuration.py
  dlt/destinations/impl/databricks/databricks.py
  dlt/destinations/impl/databricks/databricks_adapter.py
  dlt/destinations/impl/databricks/factory.py
  dlt/destinations/impl/databricks/typing.py
  docs/website/docs/dlt-ecosystem/destinations/databricks.md
  tests/.dlt/config.toml
  tests/load/databricks/test_databricks_adapter.py
Labels: enhancement

#2913 rest_api: fix: make ProcessingSteps filter and map fields optional
  dlt/sources/rest_api/typing.py
  tests/sources/rest_api/integration/test_processing_steps.py
Labels: bug

#2904 Bump default python version in CI from 3.10 to 3.11
  .github/workflows/test_common.yml
  .github/workflows/test_destinations_local.yml
  .github/workflows/test_destinations_remote.yml
  .github/workflows/test_docs_snippets.yml
  .github/workflows/test_examples.yml
  .github/workflows/test_plus.yml
  .github/workflows/test_sources_local.yml
  .github/workflows/test_tools_airflow.yml
  .github/workflows/test_tools_build_images.yml
  .github/workflows/test_tools_dbt_cloud.yml
  .github/workflows/test_tools_dbt_runner.yml
  .github/workflows/tools_deploy_notebooks.yml
Labels: tech-debt

#2789 Enable and test python 3.14 support
  .github/workflows/test_common.yml
  README.md
  pyproject.toml
  tests/common/test_typing.py
  tests/plugins/dlt_example_plugin/pyproject.toml
  uv.lock
Labels: enhancement

#2927 fix sync destination warning logging call
  dlt/pipeline/pipeline.py
Labels: bug

#2925 docs: rest_api: add tip for escaping curly braces
  docs/website/docs/dlt-ecosystem/verified-sources/rest_api/basic.md
Labels: documentation

#2916 link to add_map and add_yield_map usage example
  docs/website/docs/general-usage/resource.md
Labels: documentation
